-- Snowflake360 :: CURATED schema, scripted from the live account.
--
-- Captured as a baseline because these objects were created ad hoc during
-- development and their definitions existed only inside the account. This file
-- is the reproducible record; the numbered files in sql/ remain the source of
-- truth for anything created after it.
--
-- Originally scripted from a live SF360 deployment, then hand-corrected.
--
-- ---------------------------------------------------------------------------
-- Two things here look like mistakes and are not. Both were re-examined in an
-- audit and confirmed correct; changing either would break the pipeline.
--
-- 1. Every dynamic table is REFRESH_MODE = FULL, and that is forced rather than
--    chosen carelessly. Each one projects CURRENT_TIMESTAMP() AS BUILT_AT, and a
--    timestamp function in a SELECT list is not supported for incremental
--    refresh -- it is only incremental-safe inside a WHERE filter. SHOW DYNAMIC
--    TABLES confirms the intent: configured_refresh_mode is FULL and
--    refresh_mode_reason is empty, meaning Snowflake never had to fall back.
--    Making one incremental is also not a local decision, because an incremental
--    dynamic table cannot depend on a FULL one, so it would cascade through the
--    whole graph.
--
-- 2. TARGET_LAG = '1 day' is inert, because every table has
--    scheduling_state = SUSPENDED. Nothing self-refreshes. Refreshes are driven
--    in dependency order by CURATED.SP_REFRESH_CURATED, called from
--    TSK_SF360_CURATED once the landing rebuild has finished. That hand-ordering
--    is not redundant with TARGET_LAG = DOWNSTREAM: DOWNSTREAM requires an active
--    schedule, and the landing tables it all depends on are rebuilt by a task
--    rather than being dynamic tables themselves.
-- ---------------------------------------------------------------------------

USE DATABASE SF360;

-- IF NOT EXISTS rather than CREATE OR REPLACE, for the same reason as LANDING:
-- replacing the schema drops everything in it wholesale, which makes the file's
-- ordering irrelevant and its effect on a live install far larger than intended.
CREATE SCHEMA IF NOT EXISTS SF360.CURATED COMMENT='Curated dimensional and fact models over ACCOUNT_USAGE';
--
-- Object order in this file is DEPENDENCY order, not the alphabetical order GET_DDL
-- produced. Alphabetical put FCT_CONTRACT_POSITION (C) ahead of FCT_DAILY_CURRENCY
-- (D) even though it selects from it, so a cold install failed with:
--
--   002003 (42S02): Object 'SF360.CURATED.FCT_DAILY_CURRENCY' does not exist
--
-- and the four views, all alphabetically ahead of tables they read, failed the same
-- way. The order below is the one CURATED.SP_REFRESH_CURATED already used to refresh
-- them: dimensions, then rates, then facts, then contract position and projection,
-- then freshness, then the views, then the procedure itself.

create or replace dynamic table SF360.CURATED.DIM_ACCOUNT(
	ACCOUNT_KEY,
	ACCOUNT_LOCATOR,
	REGION,
	REGION_GROUP,
	ACCOUNT_NAME,
	ORGANIZATION_NAME,
	EDITION_RAW,
	SERVICE_LEVEL,
	CLOUD,
	CREATED_DATE,
	DELETED_DATE,
	MOVED_DATE,
	ALTERED_DATE,
	IS_DELETED,
	IS_MOVED,
	IS_MANAGED,
	PARENT_ACCOUNT,
	IS_ORG_ADMIN,
	IS_LOCKED,
	IS_GOV_REGION,
	IS_NON_PUBLIC_REGION_GROUP,
	IS_INSTALLED_ACCOUNT,
	IS_IN_SCOPE,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
WITH scope AS (SELECT ACCOUNT_NAME FROM SF360.CONFIG.ACCOUNT_SCOPE WHERE IS_INCLUDED),
scope_empty AS (SELECT (COUNT(*)=0) AS ALL_ACCT FROM scope)
SELECT
  a.ACCOUNT_LOCATOR || '|' || a.REGION            AS ACCOUNT_KEY,
  a.ACCOUNT_LOCATOR, a.REGION, a.REGION_GROUP,
  COALESCE(a.ACCOUNT_NAME, '(unnamed:' || a.ACCOUNT_LOCATOR || ')') AS ACCOUNT_NAME,
  a.ORGANIZATION_NAME,
  a.EDITION                                       AS EDITION_RAW,
  CASE a.EDITION
    WHEN 'STANDARD'          THEN 'Standard'
    WHEN 'ENTERPRISE'        THEN 'Enterprise'
    WHEN 'BUSINESS_CRITICAL' THEN 'Business Critical'
    WHEN 'VPS'               THEN 'VPS'
    ELSE INITCAP(REPLACE(a.EDITION, '_', ' '))
  END                                             AS SERVICE_LEVEL,
  SPLIT_PART(a.REGION, '_', 1)                    AS CLOUD,
  a.CREATED_ON::DATE AS CREATED_DATE, a.DELETED_ON::DATE AS DELETED_DATE,
  a.MOVED_ON::DATE   AS MOVED_DATE,   a.ALTERED_ON::DATE AS ALTERED_DATE,
  (a.DELETED_ON IS NOT NULL)                      AS IS_DELETED,
  (a.MOVED_ON IS NOT NULL)                        AS IS_MOVED,
  COALESCE(a.IS_MANAGED, FALSE)                   AS IS_MANAGED,
  a.PARENT_ACCOUNT, a.IS_ORG_ADMIN, a.IS_LOCKED,
  (a.REGION_GROUP ILIKE '%GOV%')                  AS IS_GOV_REGION,
  (a.REGION_GROUP <> 'PUBLIC')                    AS IS_NON_PUBLIC_REGION_GROUP,
  (a.ACCOUNT_NAME = CURRENT_ACCOUNT_NAME())       AS IS_INSTALLED_ACCOUNT,
  CASE WHEN (SELECT ALL_ACCT FROM scope_empty) THEN TRUE
       WHEN a.ACCOUNT_NAME IN (SELECT ACCOUNT_NAME FROM scope) THEN TRUE
       ELSE FALSE END                             AS IS_IN_SCOPE,
  CURRENT_TIMESTAMP()                             AS BUILT_AT
FROM SF360.LANDING.LND_ORG_ACCOUNTS a;
create or replace dynamic table SF360.CURATED.DIM_SERVICE_TYPE(
	SERVICE_TYPE,
	RATE_SHEET_SERVICE_TYPE,
	RATING_TYPE,
	CREDIT_CLASS,
	CATEGORY,
	DISPLAY_GROUP,
	DISPLAY_NAME,
	IS_ALIASED,
	IS_UNRATED,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
WITH known AS (
  SELECT SERVICE_TYPE, RATING_TYPE FROM SF360.LANDING.LND_ORG_SERVICE_TYPES
  UNION
  SELECT DISTINCT SERVICE_TYPE, RATING_TYPE FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY
  WHERE RATING_TYPE IS NOT NULL
),
ranked AS (
  SELECT SERVICE_TYPE, RATING_TYPE,
         ROW_NUMBER() OVER (PARTITION BY SERVICE_TYPE ORDER BY RATING_TYPE) AS RN
  FROM known
),
resolved AS (SELECT SERVICE_TYPE, RATING_TYPE FROM ranked WHERE RN = 1),
metered AS (
  SELECT DISTINCT SERVICE_TYPE FROM SF360.LANDING.LND_METERING_DAILY
  UNION SELECT DISTINCT SERVICE_TYPE FROM SF360.LANDING.LND_ORG_METERING_DAILY
),
allt AS (SELECT SERVICE_TYPE FROM resolved UNION SELECT SERVICE_TYPE FROM metered),
aliased AS (
  SELECT a.SERVICE_TYPE,
         CASE a.SERVICE_TYPE
           WHEN 'PIPE'                   THEN 'SNOWPIPE'
           WHEN 'AUTO_CLUSTERING'        THEN 'AUTOMATIC_CLUSTERING'
           WHEN 'CORTEX_CODE_DESKTOP'    THEN 'SNOWFLAKE_COCO_DESKTOP'
           WHEN 'CORTEX_CODE_CLI'        THEN 'SNOWFLAKE_COCO_CLI'
           WHEN 'CORTEX_CODE_SNOWSIGHT'  THEN 'SNOWFLAKE_COCO_SNOWSIGHT'
           WHEN 'SNOWFLAKE_INTELLIGENCE' THEN 'SNOWFLAKE_COWORK'
           WHEN 'BATCH_CORTEX_SEARCH'    THEN 'CORTEX_SEARCH'
           ELSE a.SERVICE_TYPE
         END AS RATE_SHEET_SERVICE_TYPE
  FROM allt a
),
final AS (
  SELECT x.SERVICE_TYPE, x.RATE_SHEET_SERVICE_TYPE,
         COALESCE(rd.RATING_TYPE, ra.RATING_TYPE) AS RATING_TYPE
  FROM aliased x
  LEFT JOIN resolved rd ON rd.SERVICE_TYPE = x.SERVICE_TYPE
  LEFT JOIN resolved ra ON ra.SERVICE_TYPE = x.RATE_SHEET_SERVICE_TYPE
)
SELECT
  f.SERVICE_TYPE,
  f.RATE_SHEET_SERVICE_TYPE,
  f.RATING_TYPE,
  CASE WHEN f.RATING_TYPE = 'AI_COMPUTE' THEN 'AI' ELSE 'PLATFORM' END AS CREDIT_CLASS,
  CASE
    WHEN f.RATING_TYPE IN ('STORAGE','ARCHIVE_STORAGE','HYBRID_TABLE_STORAGE','BLOCK_STORAGE',
                           'POSTGRES_STORAGE','POSTGRES_STORAGE_HA')  THEN 'STORAGE'
    WHEN f.RATING_TYPE IN ('COMPUTE','AI_COMPUTE')                    THEN 'COMPUTE'
    WHEN f.RATING_TYPE IS NULL AND f.SERVICE_TYPE ILIKE '%STORAGE%'   THEN 'STORAGE'
    WHEN f.RATING_TYPE IS NULL                                        THEN 'OTHER'
    ELSE 'OTHER'
  END AS CATEGORY,
  CASE
    WHEN f.SERVICE_TYPE IN ('CORTEX_CODE_DESKTOP','SNOWFLAKE_COCO_DESKTOP',
                            'CORTEX_CODE_CLI','SNOWFLAKE_COCO_CLI',
                            'CORTEX_CODE_SNOWSIGHT','SNOWFLAKE_COCO_SNOWSIGHT') THEN 'Cortex Code'
    WHEN f.SERVICE_TYPE IN ('CORTEX_SEARCH','BATCH_CORTEX_SEARCH')              THEN 'Cortex Search'
    WHEN f.SERVICE_TYPE IN ('POSTGRES_COMPUTE','POSTGRES_COMPUTE_HA',
                            'POSTGRES_STORAGE','POSTGRES_STORAGE_HA')           THEN 'Postgres'
    WHEN f.SERVICE_TYPE IN ('SNOWFLAKE_INTELLIGENCE','SNOWFLAKE_COWORK','SNOWWORK') THEN 'CoWork'
    WHEN f.SERVICE_TYPE IN ('PIPE','SNOWPIPE')                                  THEN 'Snowpipe'
    WHEN f.SERVICE_TYPE IN ('AUTO_CLUSTERING','AUTOMATIC_CLUSTERING')           THEN 'Reclustering'
    ELSE INITCAP(REPLACE(f.SERVICE_TYPE, '_', ' '))
  END AS DISPLAY_GROUP,
  INITCAP(REPLACE(f.SERVICE_TYPE, '_', ' ')) AS DISPLAY_NAME,
  (f.SERVICE_TYPE <> f.RATE_SHEET_SERVICE_TYPE) AS IS_ALIASED,
  (f.RATING_TYPE IS NULL)                       AS IS_UNRATED,
  CURRENT_TIMESTAMP() AS BUILT_AT
FROM final f;
create or replace dynamic table SF360.CURATED.DIM_DATE(
	DATE_UTC,
	CAL_YEAR,
	CAL_MONTH,
	CAL_MONTH_START,
	CAL_MONTH_LABEL,
	CAL_QUARTER,
	DAY_OF_WEEK,
	DAY_NAME,
	IS_WEEKEND,
	DAYS_IN_MONTH,
	FISCAL_YEAR,
	FISCAL_MONTH_NUM,
	FISCAL_QUARTER_NUM,
	FISCAL_LABEL_YEAR,
	FISCAL_QUARTER_LABEL,
	FISCAL_YEAR_LABEL,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
WITH bounds AS (
  SELECT LEAST(
           (SELECT MIN(USAGE_DATE_UTC) FROM SF360.LANDING.LND_METERING_DAILY),
           (SELECT MIN(CONTRACT_START_DATE) FROM SF360.CONFIG.CONTRACT)
         ) AS D0,
         GREATEST(
           (SELECT MAX(USAGE_DATE_UTC) FROM SF360.LANDING.LND_METERING_DAILY),
           (SELECT MAX(CONTRACT_END_DATE) FROM SF360.CONFIG.CONTRACT)
         ) AS D1
),
gen AS (
  SELECT DATEADD('day', SEQ4(), (SELECT D0 FROM bounds)) AS DATE_UTC
  FROM TABLE(GENERATOR(ROWCOUNT => 5000))
),
lim AS (
  SELECT DATE_UTC FROM gen WHERE DATE_UTC <= (SELECT D1 FROM bounds)
),
fiscal AS (
  SELECT DATE_UTC,
         CASE WHEN MONTH(DATE_UTC) >= 2 THEN YEAR(DATE_UTC) + 1 ELSE YEAR(DATE_UTC) END AS FISCAL_YEAR,
         CASE WHEN MONTH(DATE_UTC) >= 2 THEN MONTH(DATE_UTC) - 1 ELSE 12 END            AS FISCAL_MONTH_NUM,
         CASE WHEN MONTH(DATE_UTC) >= 2 THEN YEAR(DATE_UTC) ELSE YEAR(DATE_UTC) - 1 END AS FISCAL_LABEL_YEAR
  FROM lim
)
SELECT
  DATE_UTC,
  YEAR(DATE_UTC)                                    AS CAL_YEAR,
  MONTH(DATE_UTC)                                   AS CAL_MONTH,
  DATE_TRUNC('month', DATE_UTC)                     AS CAL_MONTH_START,
  TO_CHAR(DATE_UTC, 'YYYY-MM')                      AS CAL_MONTH_LABEL,
  QUARTER(DATE_UTC)                                 AS CAL_QUARTER,
  DAYOFWEEK(DATE_UTC)                               AS DAY_OF_WEEK,
  DAYNAME(DATE_UTC)                                 AS DAY_NAME,
  (DAYOFWEEK(DATE_UTC) IN (0,6))                    AS IS_WEEKEND,
  DAY(LAST_DAY(DATE_UTC))                           AS DAYS_IN_MONTH,
  FISCAL_YEAR,
  FISCAL_MONTH_NUM,
  CEIL(FISCAL_MONTH_NUM / 3.0)::NUMBER              AS FISCAL_QUARTER_NUM,
  FISCAL_LABEL_YEAR,
  FISCAL_LABEL_YEAR || '-Q' || CEIL(FISCAL_MONTH_NUM / 3.0)::NUMBER AS FISCAL_QUARTER_LABEL,
  'FY' || FISCAL_YEAR                               AS FISCAL_YEAR_LABEL,
  CURRENT_TIMESTAMP()                               AS BUILT_AT
FROM fiscal;
create or replace dynamic table SF360.CURATED.FCT_RATE_EFFECTIVE(
	ACCOUNT_KEY,
	ACCOUNT_LOCATOR,
	REGION,
	ACCOUNT_NAME,
	CONTRACT_NUMBER,
	SERVICE_LEVEL,
	RATE_DATE,
	RATE_SHEET_SERVICE_TYPE,
	RATING_TYPE,
	CURRENCY,
	EFFECTIVE_RATE,
	ADJUSTMENT_RATE,
	RATE_ROWS,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
SELECT
  ACCOUNT_KEY, ACCOUNT_LOCATOR, REGION, ACCOUNT_NAME,
  CONTRACT_NUMBER, SERVICE_LEVEL,
  RATE_DATE,
  SERVICE_TYPE                                 AS RATE_SHEET_SERVICE_TYPE,
  RATING_TYPE,
  CURRENCY,
  -- Exclude adjustment rows: they carry a rate for the rebate line, not for consumption
  MAX(CASE WHEN NOT IS_ADJUSTMENT THEN EFFECTIVE_RATE END) AS EFFECTIVE_RATE,
  MAX(CASE WHEN IS_ADJUSTMENT     THEN EFFECTIVE_RATE END) AS ADJUSTMENT_RATE,
  COUNT(*)                                     AS RATE_ROWS,
  CURRENT_TIMESTAMP()                          AS BUILT_AT
FROM SF360.LANDING.LND_ORG_RATE_SHEET
GROUP BY 1,2,3,4,5,6,7,8,9,10;
create or replace dynamic table SF360.CURATED.FCT_DAILY_CREDITS(
	SCOPE,
	ACCOUNT_KEY,
	ACCOUNT_LOCATOR,
	REGION,
	ACCOUNT_NAME,
	SERVICE_LEVEL,
	IS_DELETED,
	IS_MANAGED,
	IS_GOV_REGION,
	USAGE_DATE_UTC,
	SERVICE_TYPE,
	RATING_TYPE,
	CREDIT_CLASS,
	CATEGORY,
	DISPLAY_GROUP,
	DISPLAY_NAME,
	CREDITS_USED_COMPUTE,
	CREDITS_USED_CLOUD_SERVICES,
	CREDITS_USED,
	CREDITS_ADJUSTMENT_CLOUD_SERVICES,
	CREDITS_BILLED,
	DOLLARS_FROM_RATE,
	EFFECTIVE_RATE,
	UNPRICED_ROWS,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
SELECT
  'ORG'                        AS SCOPE,
  m.ACCOUNT_KEY, m.ACCOUNT_LOCATOR, m.REGION, m.ACCOUNT_NAME,
  a.SERVICE_LEVEL, a.IS_DELETED, a.IS_MANAGED, a.IS_GOV_REGION,
  m.USAGE_DATE_UTC,
  m.SERVICE_TYPE,
  d.RATING_TYPE, d.CREDIT_CLASS, d.CATEGORY, d.DISPLAY_GROUP, d.DISPLAY_NAME,
  SUM(m.CREDITS_USED_COMPUTE)              AS CREDITS_USED_COMPUTE,
  SUM(m.CREDITS_USED_CLOUD_SERVICES)       AS CREDITS_USED_CLOUD_SERVICES,
  SUM(m.CREDITS_USED)                      AS CREDITS_USED,
  SUM(m.CREDITS_ADJUSTMENT_CLOUD_SERVICES) AS CREDITS_ADJUSTMENT_CLOUD_SERVICES,
  SUM(m.CREDITS_BILLED)                    AS CREDITS_BILLED,
  -- Dollars from the effective rate; CREDITS_BILLED is already net of the rebate
  SUM(m.CREDITS_BILLED * r.EFFECTIVE_RATE) AS DOLLARS_FROM_RATE,
  MAX(r.EFFECTIVE_RATE)                    AS EFFECTIVE_RATE,
  COUNT_IF(r.EFFECTIVE_RATE IS NULL)       AS UNPRICED_ROWS,
  CURRENT_TIMESTAMP()                      AS BUILT_AT
FROM SF360.LANDING.LND_ORG_METERING_DAILY m
JOIN SF360.CURATED.DIM_ACCOUNT a       ON a.ACCOUNT_KEY = m.ACCOUNT_KEY
JOIN SF360.CURATED.DIM_SERVICE_TYPE d  ON d.SERVICE_TYPE = m.SERVICE_TYPE
LEFT JOIN SF360.CURATED.FCT_RATE_EFFECTIVE r
  ON  r.ACCOUNT_KEY             = m.ACCOUNT_KEY
  AND r.RATE_DATE               = m.USAGE_DATE_UTC
  AND r.RATE_SHEET_SERVICE_TYPE = d.RATE_SHEET_SERVICE_TYPE
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16;
create or replace dynamic table SF360.CURATED.FCT_DAILY_CURRENCY(
	SCOPE,
	ACCOUNT_KEY,
	ACCOUNT_LOCATOR,
	REGION,
	ACCOUNT_NAME,
	CONTRACT_NUMBER,
	SERVICE_LEVEL,
	USAGE_DATE_UTC,
	SERVICE_TYPE,
	CREDIT_CLASS,
	CATEGORY,
	DISPLAY_GROUP,
	USAGE_TYPE,
	RATING_TYPE,
	BALANCE_SOURCE,
	CURRENCY,
	USAGE_QTY,
	USAGE_IN_CURRENCY,
	ADJUSTMENT_IN_CURRENCY,
	NET_IN_CURRENCY,
	COMMITTED_IN_CURRENCY,
	OVERAGE_IN_CURRENCY,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
SELECT
  'ORG'                          AS SCOPE,
  u.ACCOUNT_KEY, u.ACCOUNT_LOCATOR, u.REGION, u.ACCOUNT_NAME,
  u.CONTRACT_NUMBER, u.SERVICE_LEVEL,
  u.USAGE_DATE_UTC, u.SERVICE_TYPE,
  d.CREDIT_CLASS, d.CATEGORY, d.DISPLAY_GROUP,
  u.USAGE_TYPE, u.RATING_TYPE, u.BALANCE_SOURCE, u.CURRENCY,
  SUM(u.USAGE_QTY)                                    AS USAGE_QTY,
  SUM(u.USAGE_IN_CURRENCY)                            AS USAGE_IN_CURRENCY,
  SUM(u.ADJUSTMENT_IN_CURRENCY)                       AS ADJUSTMENT_IN_CURRENCY,
  SUM(u.USAGE_IN_CURRENCY + u.ADJUSTMENT_IN_CURRENCY) AS NET_IN_CURRENCY,
  SUM(CASE WHEN u.BALANCE_SOURCE='Capacity' THEN u.USAGE_IN_CURRENCY ELSE 0 END) AS COMMITTED_IN_CURRENCY,
  SUM(CASE WHEN u.BALANCE_SOURCE='Overage'  THEN u.USAGE_IN_CURRENCY ELSE 0 END) AS OVERAGE_IN_CURRENCY,
  CURRENT_TIMESTAMP()            AS BUILT_AT
FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY u
LEFT JOIN SF360.CURATED.DIM_SERVICE_TYPE d ON d.SERVICE_TYPE = u.SERVICE_TYPE
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16;
create or replace dynamic table SF360.CURATED.FCT_QUERY_ATTRIBUTION(
	SCOPE,
	ACCOUNT_KEY,
	ACCOUNT_NAME,
	USAGE_DATE_UTC,
	BUCKET,
	WAREHOUSE_NAME,
	USER_NAME,
	ROLE_NAME,
	DATABASE_NAME,
	QUERY_TYPE,
	QUERY_TAG,
	ROOT_QUERY_COUNT,
	QUERY_COUNT,
	CREDITS,
	BYTES_SCANNED,
	EXECUTION_MS,
	DOLLARS,
	RATE_SOURCE,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
WITH inst AS (
  SELECT ACCOUNT_KEY, ACCOUNT_NAME FROM SF360.CURATED.DIM_ACCOUNT WHERE IS_INSTALLED_ACCOUNT
),
sub AS (SELECT * FROM SF360.CONFIG.SUBSCRIPTION WHERE VALID_TO IS NULL AND ACCOUNT_NAME = CURRENT_ACCOUNT_NAME()),

-- Bucket 1: credits attributable to a specific query
attributed AS (
  SELECT a.USAGE_DATE_UTC, 'QUERY_ATTRIBUTED' AS BUCKET, a.WAREHOUSE_NAME,
         COALESCE(a.USER_NAME,'UNKNOWN')               AS USER_NAME,
         COALESCE(a.ROLE_NAME,'UNKNOWN')               AS ROLE_NAME,
         COALESCE(a.DATABASE_NAME,'UNKNOWN')           AS DATABASE_NAME,
         COALESCE(a.QUERY_TYPE,'UNKNOWN')              AS QUERY_TYPE,
         COALESCE(NULLIF(a.QUERY_TAG,''),'(untagged)') AS QUERY_TAG,
         COUNT(DISTINCT a.ROOT_QUERY_ID)               AS ROOT_QUERY_COUNT,
         COUNT(*)                                      AS QUERY_COUNT,
         SUM(a.CREDITS_ATTRIBUTED_COMPUTE)             AS CREDITS,
         SUM(COALESCE(a.BYTES_SCANNED,0))              AS BYTES_SCANNED,
         SUM(COALESCE(a.EXECUTION_TIME,0))             AS EXECUTION_MS
  FROM SF360.LANDING.LND_QUERY_ATTRIBUTION a
  GROUP BY 1,2,3,4,5,6,7,8
),
-- Bucket 2: warehouse credits with no query attached, scaled to billed equivalent
rebate AS (
  SELECT USAGE_DATE_UTC,
         CASE WHEN SUM(CREDITS_USED) > 0 THEN SUM(CREDITS_BILLED)/SUM(CREDITS_USED) ELSE 1 END AS F
  FROM SF360.LANDING.LND_METERING_DAILY
  WHERE SERVICE_TYPE = 'WAREHOUSE_METERING' GROUP BY 1
),
wh AS (
  SELECT w.USAGE_DATE_UTC, w.WAREHOUSE_NAME,
         SUM(w.CREDITS_USED) * COALESCE(r.F,1) AS WH_BILLED
  FROM SF360.LANDING.LND_WAREHOUSE_METERING w
  LEFT JOIN rebate r ON r.USAGE_DATE_UTC = w.USAGE_DATE_UTC
  GROUP BY w.USAGE_DATE_UTC, w.WAREHOUSE_NAME, r.F
),
wh_attr AS (
  SELECT USAGE_DATE_UTC, WAREHOUSE_NAME, SUM(CREDITS_ATTRIBUTED_COMPUTE) AS ATTR
  FROM SF360.LANDING.LND_QUERY_ATTRIBUTION GROUP BY 1,2
),
idle AS (
  SELECT t.USAGE_DATE_UTC, 'WAREHOUSE_IDLE', t.WAREHOUSE_NAME,
         '(no user)','(no role)','(no database)','(no query)','(no query)', 0, 0,
         GREATEST(t.WH_BILLED - COALESCE(a.ATTR,0), 0), 0, 0
  FROM wh t LEFT JOIN wh_attr a
    ON a.USAGE_DATE_UTC = t.USAGE_DATE_UTC AND a.WAREHOUSE_NAME = t.WAREHOUSE_NAME
),
-- Bucket 3: serverless, SPCS, AI. Never present in attribution at all.
non_wh AS (
  SELECT m.USAGE_DATE_UTC, 'NON_WAREHOUSE', d.DISPLAY_NAME,
         '(no user)','(no role)','(no database)','(serverless)','(serverless)', 0, 0,
         SUM(m.CREDITS_BILLED), 0, 0
  FROM SF360.LANDING.LND_METERING_DAILY m
  JOIN SF360.CURATED.DIM_SERVICE_TYPE d ON d.SERVICE_TYPE = m.SERVICE_TYPE
  WHERE m.SERVICE_TYPE <> 'WAREHOUSE_METERING'
  GROUP BY 1,2,3
),
allb AS (SELECT * FROM attributed UNION ALL SELECT * FROM idle UNION ALL SELECT * FROM non_wh)
SELECT
  'ACCOUNT'                      AS SCOPE,
  i.ACCOUNT_KEY, i.ACCOUNT_NAME,
  b.*,
  b.CREDITS * s.PRICE_PER_PLATFORM_CREDIT AS DOLLARS,
  s.RATE_SOURCE,
  CURRENT_TIMESTAMP()            AS BUILT_AT
FROM allb b CROSS JOIN inst i CROSS JOIN sub s
WHERE b.CREDITS > 0;
create or replace dynamic table SF360.CURATED.FCT_ANOMALY_DAILY(
	SCOPE,
	ACCOUNT_KEY,
	ACCOUNT_NAME,
	REGION,
	ANOMALY_DATE,
	ANOMALY_ID,
	IS_ANOMALY,
	MEASURE_TYPE,
	UNIT,
	ACTUAL_VALUE,
	FORECASTED_VALUE,
	LOWER_BOUND,
	UPPER_BOUND,
	NATIVE_FORECAST_WAS_NEGATIVE,
	VARIANCE_VS_FORECAST,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
SELECT
  'ORG'                         AS SCOPE,
  o.ACCOUNT_KEY, o.ACCOUNT_NAME, o.REGION,
  o.ANOMALY_DATE, o.ANOMALY_ID, o.IS_ANOMALY,
  'CURRENCY'                    AS MEASURE_TYPE,
  o.CURRENCY                    AS UNIT,
  o.ACTUAL_VALUE,
  o.FORECASTED_VALUE_FLOORED    AS FORECASTED_VALUE,
  o.LOWER_BOUND_FLOORED         AS LOWER_BOUND,
  o.UPPER_BOUND,
  (o.FORECASTED_VALUE_RAW < 0)  AS NATIVE_FORECAST_WAS_NEGATIVE,
  o.ACTUAL_VALUE - o.FORECASTED_VALUE_FLOORED AS VARIANCE_VS_FORECAST,
  CURRENT_TIMESTAMP()           AS BUILT_AT
FROM SF360.LANDING.LND_ORG_ANOMALIES o

UNION ALL

SELECT
  'ACCOUNT',
  d.ACCOUNT_KEY, a.ACCOUNT_NAME, d.REGION,
  a.ANOMALY_DATE, a.ANOMALY_ID, a.IS_ANOMALY,
  'CREDITS', 'credits',
  a.ACTUAL_VALUE,
  a.FORECASTED_VALUE_FLOORED,
  a.LOWER_BOUND_FLOORED,
  a.UPPER_BOUND,
  (a.FORECASTED_VALUE_RAW < 0),
  a.ACTUAL_VALUE - a.FORECASTED_VALUE_FLOORED,
  CURRENT_TIMESTAMP()
FROM SF360.LANDING.LND_ACCT_ANOMALIES a
LEFT JOIN SF360.CURATED.DIM_ACCOUNT d
  ON d.ACCOUNT_NAME = a.ACCOUNT_NAME AND d.IS_INSTALLED_ACCOUNT;
create or replace dynamic table SF360.CURATED.FCT_OPTIMIZATION_OPPORTUNITY(
	SCOPE,
	ACCOUNT_NAME,
	INSIGHT_DATE,
	INSIGHT_TOPIC,
	INSIGHT_TYPE_ID,
	IS_OPPORTUNITY,
	WAREHOUSE_NAME,
	WAREHOUSE_ID,
	QUERY_ID,
	QUERY_PARAMETERIZED_HASH,
	TOTAL_ELAPSED_TIME,
	MESSAGE_VARIANT,
	SUGGESTIONS_VARIANT,
	MESSAGE_TEXT,
	SUGGESTION_COUNT,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
SELECT
  'ACCOUNT'                       AS SCOPE,
  q.ACCOUNT_NAME,
  q.START_TIME::DATE              AS INSIGHT_DATE,
  q.INSIGHT_TOPIC,
  q.INSIGHT_TYPE_ID,
  q.IS_OPPORTUNITY,
  q.WAREHOUSE_NAME,
  q.WAREHOUSE_ID,
  q.QUERY_ID,
  q.QUERY_PARAMETERIZED_HASH,
  q.TOTAL_ELAPSED_TIME,
  -- MESSAGE and SUGGESTIONS are semi-structured; casting to VARCHAR yields [object Object]
  q.MESSAGE                       AS MESSAGE_VARIANT,
  q.SUGGESTIONS                   AS SUGGESTIONS_VARIANT,
  TO_VARCHAR(GET(q.MESSAGE, 'message'))     AS MESSAGE_TEXT,
  ARRAY_SIZE(TRY_CAST(q.SUGGESTIONS AS ARRAY)) AS SUGGESTION_COUNT,
  CURRENT_TIMESTAMP()             AS BUILT_AT
FROM SF360.LANDING.LND_QUERY_INSIGHTS q;
create or replace dynamic table SF360.CURATED.FCT_CONTRACT_POSITION(
	SCOPE,
	ORGANIZATION_NAME,
	CONTRACT_NUMBER,
	USAGE_DATE_UTC,
	CONTRACT_START_DATE,
	CONTRACT_END_DATE,
	CAPACITY_PURCHASED,
	METERED_CURRENCY,
	DOLLARS_DAY,
	COMMITTED_DAY,
	OVERAGE_DAY,
	ACCOUNTS_WITH_SPEND,
	DAY_INDEX,
	CAPACITY_USED,
	TOTAL_CAPACITY_USED,
	REMAINING_BALANCE,
	IS_PAST_CAPACITY,
	DAYS_REMAINING_IN_TERM,
	CONTRACT_SOURCE,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
WITH c AS (
  SELECT * FROM SF360.CONFIG.CONTRACT WHERE VALID_TO IS NULL AND IS_ACTIVE
),
as_of AS (
  -- Exclude the in-progress day: currency for today is partial
  SELECT DATEADD('day', -1, MAX(USAGE_DATE_UTC)) AS MAX_CLOSED_DATE
  FROM SF360.CURATED.FCT_DAILY_CURRENCY
),
daily AS (
  SELECT f.USAGE_DATE_UTC,
         SUM(f.NET_IN_CURRENCY)       AS DOLLARS_DAY,
         SUM(f.COMMITTED_IN_CURRENCY) AS COMMITTED_DAY,
         SUM(f.OVERAGE_IN_CURRENCY)   AS OVERAGE_DAY,
         COUNT(DISTINCT f.ACCOUNT_KEY) AS ACCOUNTS_WITH_SPEND
  FROM SF360.CURATED.FCT_DAILY_CURRENCY f
  CROSS JOIN c
  WHERE f.USAGE_DATE_UTC BETWEEN c.CONTRACT_START_DATE AND c.CONTRACT_END_DATE
    AND f.USAGE_DATE_UTC <= (SELECT MAX_CLOSED_DATE FROM as_of)
  GROUP BY 1
),
spine AS (
  SELECT d.DATE_UTC AS USAGE_DATE_UTC,
         COALESCE(dd.DOLLARS_DAY,0)   AS DOLLARS_DAY,
         COALESCE(dd.COMMITTED_DAY,0) AS COMMITTED_DAY,
         COALESCE(dd.OVERAGE_DAY,0)   AS OVERAGE_DAY,
         COALESCE(dd.ACCOUNTS_WITH_SPEND,0) AS ACCOUNTS_WITH_SPEND
  FROM SF360.CURATED.DIM_DATE d
  CROSS JOIN c
  LEFT JOIN daily dd ON dd.USAGE_DATE_UTC = d.DATE_UTC
  WHERE d.DATE_UTC BETWEEN c.CONTRACT_START_DATE AND c.CONTRACT_END_DATE
    AND d.DATE_UTC <= (SELECT MAX_CLOSED_DATE FROM as_of)
),
cume AS (
  SELECT USAGE_DATE_UTC, DOLLARS_DAY, COMMITTED_DAY, OVERAGE_DAY, ACCOUNTS_WITH_SPEND,
         SUM(DOLLARS_DAY) OVER (ORDER BY USAGE_DATE_UTC) AS CUME_DOLLARS,
         ROW_NUMBER()     OVER (ORDER BY USAGE_DATE_UTC) AS DAY_INDEX
  FROM spine
)
SELECT
  'ORG'                                        AS SCOPE,
  c.ORGANIZATION_NAME,
  c.CONTRACT_NUMBER,
  u.USAGE_DATE_UTC,
  c.CONTRACT_START_DATE,
  c.CONTRACT_END_DATE,
  c.CAPACITY_PURCHASED,
  c.METERED_CURRENCY,
  u.DOLLARS_DAY,
  u.COMMITTED_DAY,
  u.OVERAGE_DAY,
  u.ACCOUNTS_WITH_SPEND,
  u.DAY_INDEX,
  u.CUME_DOLLARS                               AS CAPACITY_USED,
  -- A360 capacity formula. All addends customer-entered except CAPACITY_USED.
  u.CUME_DOLLARS + c.TOTAL_FREE_USAGE + c.ROLLOVER + c.ADJUSTMENT + c.BALANCE_TRANSFER
    + c.CURRENCY_CONVERSION_ADJUSTMENT + c.DATA_SHARING_REBATE + c.BALANCE_MIGRATION
                                               AS TOTAL_CAPACITY_USED,
  c.CAPACITY_PURCHASED - (u.CUME_DOLLARS + c.TOTAL_FREE_USAGE + c.ROLLOVER + c.ADJUSTMENT
    + c.BALANCE_TRANSFER + c.CURRENCY_CONVERSION_ADJUSTMENT + c.DATA_SHARING_REBATE
    + c.BALANCE_MIGRATION)                     AS REMAINING_BALANCE,
  (u.CUME_DOLLARS > c.CAPACITY_PURCHASED)      AS IS_PAST_CAPACITY,
  DATEDIFF('day', u.USAGE_DATE_UTC, c.CONTRACT_END_DATE) AS DAYS_REMAINING_IN_TERM,
  c.CONTRACT_SOURCE,
  CURRENT_TIMESTAMP()                          AS BUILT_AT
FROM cume u CROSS JOIN c;
create or replace dynamic table SF360.CURATED.FCT_CONTRACT_PROJECTION(
	SCOPE,
	ORGANIZATION_NAME,
	CONTRACT_NUMBER,
	AS_OF_DATE,
	METHOD,
	METHOD_CLASS,
	PROJECTED_RATE_PER_DAY,
	CAPACITY_PURCHASED,
	CAPACITY_USED_TO_DATE,
	REMAINING_BALANCE,
	DAYS_REMAINING_IN_TERM,
	PROJECTED_TOTAL_AT_TERM_END,
	PROJECTED_OVERAGE,
	DAYS_UNTIL_OVERAGE,
	PROJECTED_OVERAGE_DATE,
	OVERAGE_BEFORE_TERM_END,
	CONTRACT_SOURCE,
	BUILT_AT
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
WITH latest AS (SELECT MAX(USAGE_DATE_UTC) AS AS_OF FROM SF360.CURATED.FCT_CONTRACT_POSITION),
cur AS (
  SELECT p.* FROM SF360.CURATED.FCT_CONTRACT_POSITION p
  WHERE p.USAGE_DATE_UTC = (SELECT AS_OF FROM latest)
),

run_rates AS (
  SELECT w.N AS WINDOW_DAYS, AVG(p.DOLLARS_DAY) AS RATE_PER_DAY
  FROM (SELECT 30 AS N UNION ALL SELECT 60 UNION ALL SELECT 90
        UNION ALL SELECT 180) w
  JOIN SF360.CURATED.FCT_CONTRACT_POSITION p
    ON p.USAGE_DATE_UTC >  DATEADD('day', -w.N, (SELECT AS_OF FROM latest))
   AND p.USAGE_DATE_UTC <= (SELECT AS_OF FROM latest)
  GROUP BY w.N
),

native AS (
  SELECT AVG(GREATEST(FORECASTED_VALUE_RAW, 0)) AS RATE_PER_DAY
  FROM SF360.LANDING.LND_ORG_ANOMALIES
  WHERE ANOMALY_DATE > DATEADD('day', -30, (SELECT AS_OF FROM latest))
),
methods AS (
  SELECT 'RUN_RATE_' || WINDOW_DAYS::VARCHAR || 'D' AS METHOD,
         RATE_PER_DAY, 'TRAILING_RUN_RATE' AS METHOD_CLASS
  FROM run_rates
  UNION ALL
  SELECT 'NATIVE_FORECAST_FLOORED', RATE_PER_DAY, 'SNOWFLAKE_NATIVE' FROM native
)
SELECT
  'ORG'                            AS SCOPE,
  c.ORGANIZATION_NAME,
  c.CONTRACT_NUMBER,
  c.USAGE_DATE_UTC                 AS AS_OF_DATE,
  m.METHOD,
  m.METHOD_CLASS,
  GREATEST(ROUND(m.RATE_PER_DAY, 2), 0)         AS PROJECTED_RATE_PER_DAY,
  c.CAPACITY_PURCHASED,
  ROUND(c.TOTAL_CAPACITY_USED, 2)               AS CAPACITY_USED_TO_DATE,
  ROUND(c.REMAINING_BALANCE, 2)                 AS REMAINING_BALANCE,
  c.DAYS_REMAINING_IN_TERM,
  GREATEST(ROUND(c.TOTAL_CAPACITY_USED
    + GREATEST(m.RATE_PER_DAY,0) * c.DAYS_REMAINING_IN_TERM, 2), 0) AS PROJECTED_TOTAL_AT_TERM_END,
  GREATEST(ROUND(c.TOTAL_CAPACITY_USED
    + GREATEST(m.RATE_PER_DAY,0) * c.DAYS_REMAINING_IN_TERM - c.CAPACITY_PURCHASED, 2), 0)
                                                AS PROJECTED_OVERAGE,
  CASE WHEN m.RATE_PER_DAY > 0 AND c.REMAINING_BALANCE > 0
       THEN CEIL(c.REMAINING_BALANCE / m.RATE_PER_DAY) END AS DAYS_UNTIL_OVERAGE,
  CASE WHEN m.RATE_PER_DAY > 0 AND c.REMAINING_BALANCE > 0
       THEN DATEADD('day', CEIL(c.REMAINING_BALANCE / m.RATE_PER_DAY), c.USAGE_DATE_UTC) END
                                                AS PROJECTED_OVERAGE_DATE,
  CASE WHEN m.RATE_PER_DAY > 0 AND c.REMAINING_BALANCE > 0
        AND DATEADD('day', CEIL(c.REMAINING_BALANCE / m.RATE_PER_DAY), c.USAGE_DATE_UTC)
            <= c.CONTRACT_END_DATE
       THEN TRUE ELSE FALSE END                 AS OVERAGE_BEFORE_TERM_END,
  c.CONTRACT_SOURCE,
  CURRENT_TIMESTAMP()                           AS BUILT_AT
FROM cur c CROSS JOIN methods m;
create or replace dynamic table SF360.CURATED.FCT_FRESHNESS(
	SOURCE_NAME,
	SCOPE,
	MEASURE,
	AS_OF_DATE,
	LAG_DAYS,
	DOCUMENTED_LATENCY_HOURS,
	SOURCE_VIEW
) target_lag = '1 day' refresh_mode = FULL initialize = ON_CREATE warehouse = SF360_WH
 as
SELECT 'ORG_CREDITS'   AS SOURCE_NAME, 'ORG'     AS SCOPE, 'credits'  AS MEASURE,
       MAX(USAGE_DATE_UTC) AS AS_OF_DATE,
       DATEDIFF('day', MAX(USAGE_DATE_UTC), CURRENT_DATE()) AS LAG_DAYS,
       24 AS DOCUMENTED_LATENCY_HOURS,
       'ORGANIZATION_USAGE.METERING_DAILY_HISTORY' AS SOURCE_VIEW
FROM SF360.LANDING.LND_ORG_METERING_DAILY
UNION ALL
SELECT 'ORG_CURRENCY', 'ORG', 'dollars', MAX(USAGE_DATE_UTC),
       DATEDIFF('day', MAX(USAGE_DATE_UTC), CURRENT_DATE()), 72,
       'ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY'
FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY
UNION ALL
SELECT 'ORG_BALANCE', 'ORG', 'balance', MAX(BALANCE_DATE),
       DATEDIFF('day', MAX(BALANCE_DATE), CURRENT_DATE()), 72,
       'ORGANIZATION_USAGE.REMAINING_BALANCE_DAILY'
FROM SF360.LANDING.LND_ORG_REMAINING_BALANCE
UNION ALL
SELECT 'ORG_RATES', 'ORG', 'rates', MAX(RATE_DATE),
       DATEDIFF('day', MAX(RATE_DATE), CURRENT_DATE()), 24,
       'ORGANIZATION_USAGE.RATE_SHEET_DAILY'
FROM SF360.LANDING.LND_ORG_RATE_SHEET
UNION ALL
SELECT 'ACCT_CREDITS', 'ACCOUNT', 'credits', MAX(USAGE_DATE_UTC),
       DATEDIFF('day', MAX(USAGE_DATE_UTC), CURRENT_DATE()), 3,
       'ACCOUNT_USAGE.METERING_DAILY_HISTORY'
FROM SF360.LANDING.LND_METERING_DAILY
UNION ALL
SELECT 'ACCT_ATTRIBUTION', 'ACCOUNT', 'attribution', MAX(USAGE_DATE_UTC),
       DATEDIFF('day', MAX(USAGE_DATE_UTC), CURRENT_DATE()), 8,
       'ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY'
FROM SF360.LANDING.LND_QUERY_ATTRIBUTION
UNION ALL
SELECT 'ACCT_ANOMALIES', 'ACCOUNT', 'anomalies', MAX(ANOMALY_DATE),
       DATEDIFF('day', MAX(ANOMALY_DATE), CURRENT_DATE()), 3,
       'ACCOUNT_USAGE.ANOMALIES_DAILY'
FROM SF360.LANDING.LND_ACCT_ANOMALIES
UNION ALL
SELECT 'ORG_ANOMALIES', 'ORG', 'anomalies', MAX(ANOMALY_DATE),
       DATEDIFF('day', MAX(ANOMALY_DATE), CURRENT_DATE()), 24,
       'ORGANIZATION_USAGE.ANOMALIES_IN_CURRENCY_DAILY'
FROM SF360.LANDING.LND_ORG_ANOMALIES;
create or replace view SF360.CURATED.FCT_BILLING_PERIOD_POSITION(
	CONTRACT_SK,
	CONTRACT_NUMBER,
	CURRENCY,
	BILLING_FREQUENCY,
	CADENCE_MONTHS,
	PERIOD_COUNT,
	PERIOD_SEQ,
	PERIOD_LABEL,
	PERIOD_START,
	PERIOD_END,
	DATA_COVERAGE,
	IS_CURRENT_PERIOD,
	PERIOD_DAYS,
	ELAPSED_DAYS,
	ALLOCATION,
	CONSUMPTION,
	CUM_ALLOCATION,
	CUM_CONSUMPTION,
	TOTAL_CAPACITY,
	OPENING_BALANCE,
	PERIOD_BURN_PCT,
	PROJECTED_PERIOD_BURN_PCT,
	PULL_FORWARD_TRIGGERED,
	PERIOD_OVERSPEND,
	POOLED_REMAINING,
	TERM_BURN_PCT,
	OVERAGE_AMOUNT,
	IS_IN_OVERAGE,
	CAPACITY_CREDIT_PRICE,
	ON_DEMAND_CREDIT_PRICE,
	PRICE_CLIFF_PCT,
	TERM_START,
	TERM_END,
	BUILT_AT
) COMMENT='One row per capacity installment period: allocation, measured consumption, pooled cumulative position, pull-forward trigger, and overage. DATA_COVERAGE flags periods that predate ACCOUNT_USAGE retention so absent history is never rendered as zero spend.'
 as
WITH cov AS (
  SELECT MIN(USAGE_DATE_UTC) AS FIRST_DAY, MAX(USAGE_DATE_UTC) AS LAST_DAY
  FROM SF360.CURATED.FCT_DAILY_CURRENCY
),
ct AS (
  SELECT CONTRACT_SK, CAPACITY_CREDIT_PRICE, ON_DEMAND_CREDIT_PRICE,
         INVOICE_PULL_FORWARD, CARRYOVER_MODE,
         COALESCE(PRIOR_CONSUMPTION_AMOUNT, 0) AS PRIOR_AMT,
         PRIOR_CONSUMPTION_AS_OF               AS PRIOR_AS_OF
  FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE
),


spend AS (
  SELECT
    b.CONTRACT_SK,
    b.PERIOD_SEQ,
    SUM(f.NET_IN_CURRENCY) AS MEASURED
  FROM SF360.CONFIG.BILLING_SCHEDULE b
  JOIN ct ON ct.CONTRACT_SK = b.CONTRACT_SK
  JOIN SF360.CURATED.FCT_DAILY_CURRENCY f
    ON f.USAGE_DATE_UTC BETWEEN b.PERIOD_START AND b.PERIOD_END
   AND (ct.PRIOR_AS_OF IS NULL OR f.USAGE_DATE_UTC > ct.PRIOR_AS_OF)
  WHERE b.IS_ACTIVE
  GROUP BY 1, 2
),
base AS (
  SELECT
    b.CONTRACT_SK, b.CONTRACT_NUMBER, b.CURRENCY,
    b.BILLING_FREQUENCY, b.CADENCE_MONTHS, b.PERIOD_COUNT,
    b.PERIOD_SEQ, b.PERIOD_LABEL, b.PERIOD_START, b.PERIOD_END,
    b.ALLOCATION, b.CUM_ALLOCATION, b.TOTAL_CAPACITY,
    b.TERM_START, b.TERM_END, b.IS_CURRENT_PERIOD,
    ct.CAPACITY_CREDIT_PRICE, ct.ON_DEMAND_CREDIT_PRICE,
    ct.INVOICE_PULL_FORWARD, ct.PRIOR_AMT, ct.PRIOR_AS_OF,
    COALESCE(s.MEASURED, 0) AS MEASURED_CONSUMPTION,


    CASE
      WHEN b.PERIOD_START > cov.LAST_DAY                              THEN 'FUTURE'
      WHEN b.PERIOD_END   < COALESCE(ct.PRIOR_AS_OF, cov.FIRST_DAY)   THEN 'NO_DATA'
      WHEN b.PERIOD_START < COALESCE(ct.PRIOR_AS_OF, cov.FIRST_DAY)
        OR b.PERIOD_END   > cov.LAST_DAY                              THEN 'PARTIAL'
      ELSE 'COMPLETE'
    END AS DATA_COVERAGE,

    DATEDIFF(day, b.PERIOD_START, b.PERIOD_END) + 1 AS PERIOD_DAYS,
    GREATEST(LEAST(DATEDIFF(day, b.PERIOD_START, LEAST(cov.LAST_DAY, b.PERIOD_END)) + 1,
                   DATEDIFF(day, b.PERIOD_START, b.PERIOD_END) + 1), 0) AS ELAPSED_DAYS
  FROM SF360.CONFIG.BILLING_SCHEDULE b
  JOIN ct        ON ct.CONTRACT_SK = b.CONTRACT_SK
  CROSS JOIN cov
  LEFT JOIN spend s ON s.CONTRACT_SK = b.CONTRACT_SK AND s.PERIOD_SEQ = b.PERIOD_SEQ
  WHERE b.IS_ACTIVE
),
cum AS (
  SELECT
    base.*,


    PRIOR_AMT + SUM(MEASURED_CONSUMPTION) OVER (
      PARTITION BY CONTRACT_SK ORDER BY PERIOD_SEQ
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUM_CONSUMPTION
  FROM base
)
SELECT
  CONTRACT_SK, CONTRACT_NUMBER, CURRENCY,
  BILLING_FREQUENCY, CADENCE_MONTHS, PERIOD_COUNT,
  PERIOD_SEQ, PERIOD_LABEL, PERIOD_START, PERIOD_END,
  DATA_COVERAGE, IS_CURRENT_PERIOD, PERIOD_DAYS, ELAPSED_DAYS,

  ALLOCATION,



  IFF(DATA_COVERAGE IN ('NO_DATA','FUTURE'), NULL, MEASURED_CONSUMPTION) AS CONSUMPTION,
  CUM_ALLOCATION,
  CUM_CONSUMPTION,
  TOTAL_CAPACITY,
  PRIOR_AMT AS OPENING_BALANCE,


  IFF(DATA_COVERAGE IN ('NO_DATA','FUTURE') OR ALLOCATION = 0, NULL,
      ROUND(MEASURED_CONSUMPTION / ALLOCATION * 100, 2))     AS PERIOD_BURN_PCT,


  IFF(IS_CURRENT_PERIOD AND ELAPSED_DAYS > 0 AND ALLOCATION > 0,
      ROUND(MEASURED_CONSUMPTION / ELAPSED_DAYS * PERIOD_DAYS / ALLOCATION * 100, 2),
      NULL)                                                  AS PROJECTED_PERIOD_BURN_PCT,



  IFF(DATA_COVERAGE IN ('NO_DATA','FUTURE'), NULL,
      INVOICE_PULL_FORWARD AND MEASURED_CONSUMPTION > ALLOCATION)
                                                             AS PULL_FORWARD_TRIGGERED,
  IFF(DATA_COVERAGE <> 'NO_DATA' AND MEASURED_CONSUMPTION > ALLOCATION,
      ROUND(MEASURED_CONSUMPTION - ALLOCATION, 2), 0)        AS PERIOD_OVERSPEND,


  ROUND(TOTAL_CAPACITY - CUM_CONSUMPTION, 2)                 AS POOLED_REMAINING,
  ROUND(CUM_CONSUMPTION / NULLIF(TOTAL_CAPACITY,0) * 100, 2) AS TERM_BURN_PCT,



  GREATEST(ROUND(CUM_CONSUMPTION - TOTAL_CAPACITY, 2), 0)    AS OVERAGE_AMOUNT,
  CUM_CONSUMPTION > TOTAL_CAPACITY                           AS IS_IN_OVERAGE,

  CAPACITY_CREDIT_PRICE, ON_DEMAND_CREDIT_PRICE,
  ROUND((ON_DEMAND_CREDIT_PRICE / NULLIF(CAPACITY_CREDIT_PRICE,0) - 1) * 100, 2)
                                                             AS PRICE_CLIFF_PCT,
  TERM_START, TERM_END,
  CURRENT_TIMESTAMP()                                        AS BUILT_AT
FROM cum;
create or replace view SF360.CURATED.FCT_CAPACITY_WARNING(
	WARNING_CODE,
	WARNING_TITLE,
	SEVERITY,
	SORT_ORDER,
	DAYS_UNTIL,
	IMPACT_DATE,
	MESSAGE,
	RECOMMENDATION,
	METRIC_VALUE,
	CONTRACT_NUMBER,
	CURRENCY,
	RATE_BASIS,
	DAYS_OF_HISTORY,
	IS_LOW_CONFIDENCE,
	CURRENT_PERIOD_COVERAGE,
	BUILT_AT
) COMMENT='One row per active forward-looking capacity warning, with severity, days until impact, and a plain-language recommendation. Drives the warning banner at the top of the Active Contract page.'
 as
WITH rate AS (


  SELECT
    COALESCE(
      MAX(IFF(METHOD = 'NATIVE_FORECAST_FLOORED', PROJECTED_RATE_PER_DAY, NULL)),
      MAX(IFF(METHOD = 'RUN_RATE_30D',            PROJECTED_RATE_PER_DAY, NULL))
    ) AS RATE_PER_DAY,
    IFF(MAX(IFF(METHOD = 'NATIVE_FORECAST_FLOORED', PROJECTED_RATE_PER_DAY, NULL)) IS NOT NULL,
        'Snowflake ML forecast', 'trailing 30-day run rate') AS RATE_BASIS,
    MAX(AS_OF_DATE) AS AS_OF_DATE
  FROM SF360.CURATED.FCT_CONTRACT_PROJECTION
),



hist AS (
  SELECT COUNT(DISTINCT USAGE_DATE_UTC) AS DAYS_OF_HISTORY
  FROM SF360.CURATED.FCT_DAILY_CURRENCY
),
cur AS (
  SELECT * FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION WHERE IS_CURRENT_PERIOD
),
term AS (
  SELECT
    MAX(TOTAL_CAPACITY)  AS TOTAL_CAPACITY,
    MAX(TERM_END)        AS TERM_END,
    MAX(CONTRACT_NUMBER) AS CONTRACT_NUMBER,
    MAX(CURRENCY)        AS CURRENCY,

    MAX(IFF(IS_CURRENT_PERIOD, CUM_CONSUMPTION,   NULL)) AS CUM_CONSUMPTION,
    MAX(IFF(IS_CURRENT_PERIOD, POOLED_REMAINING,  NULL)) AS POOLED_REMAINING,
    MAX(IFF(IS_CURRENT_PERIOD, TERM_BURN_PCT,     NULL)) AS TERM_BURN_PCT,
    MAX(IFF(IS_CURRENT_PERIOD, IS_IN_OVERAGE,     NULL)) AS IS_IN_OVERAGE,
    MAX(CAPACITY_CREDIT_PRICE)  AS CAPACITY_CREDIT_PRICE,
    MAX(ON_DEMAND_CREDIT_PRICE) AS ON_DEMAND_CREDIT_PRICE,
    MAX(PRICE_CLIFF_PCT)        AS PRICE_CLIFF_PCT
  FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION
),
ctx AS (
  SELECT
    t.*, r.RATE_PER_DAY, r.RATE_BASIS, r.AS_OF_DATE, h.DAYS_OF_HISTORY,
    c.PERIOD_LABEL, c.PERIOD_START, c.PERIOD_END, c.ALLOCATION,
    c.CONSUMPTION AS PERIOD_CONSUMPTION, c.PERIOD_BURN_PCT,
    c.PROJECTED_PERIOD_BURN_PCT, c.PULL_FORWARD_TRIGGERED,
    c.ELAPSED_DAYS, c.PERIOD_DAYS, c.DATA_COVERAGE,
    DATEDIFF(day, CURRENT_DATE(), t.TERM_END) AS DAYS_LEFT_IN_TERM,

    IFF(r.RATE_PER_DAY > 0 AND t.POOLED_REMAINING > 0,
        FLOOR(t.POOLED_REMAINING / r.RATE_PER_DAY), NULL) AS DAYS_TO_EXHAUSTION
  FROM term t CROSS JOIN rate r CROSS JOIN hist h
  LEFT JOIN cur c ON TRUE
),
enriched AS (
  SELECT ctx.*,
    IFF(DAYS_TO_EXHAUSTION IS NOT NULL,
        DATEADD(day, DAYS_TO_EXHAUSTION, CURRENT_DATE()), NULL) AS EXHAUSTION_DATE
  FROM ctx
),
w AS (

  SELECT
    'PERIOD_BURN_HOT' AS WARNING_CODE,
    'Period burning hot' AS WARNING_TITLE,
    IFF(PROJECTED_PERIOD_BURN_PCT >= 150, 'CRITICAL', 'WARNING') AS SEVERITY,
    1 AS SORT_ORDER,
    GREATEST(DATEDIFF(day, CURRENT_DATE(), PERIOD_END), 0) AS DAYS_UNTIL,
    PERIOD_END AS IMPACT_DATE,
    PERIOD_LABEL || ' is pacing to '
      || TO_VARCHAR(PROJECTED_PERIOD_BURN_PCT, '999,990') || '% of its '
      || CURRENCY || ' ' || TO_VARCHAR(ALLOCATION, '999,999,990') || ' allocation.'
      AS MESSAGE,
    'Spend in this installment period is outrunning the amount invoiced for it. '
      || 'Review the largest warehouses and AI workloads before the period closes.'
      AS RECOMMENDATION,
    PROJECTED_PERIOD_BURN_PCT AS METRIC_VALUE
  FROM enriched
  WHERE PROJECTED_PERIOD_BURN_PCT > 100 AND DAYS_OF_HISTORY >= 14

  UNION ALL

  SELECT
    'PULL_FORWARD_LIKELY',
    'Next invoice may arrive early',
    'WARNING', 2,
    0, CURRENT_DATE(),
    PERIOD_LABEL || ' has consumed ' || CURRENCY || ' '
      || TO_VARCHAR(PERIOD_CONSUMPTION, '999,999,990') || ' against a '
      || TO_VARCHAR(ALLOCATION, '999,999,990') || ' installment, exceeding it by '
      || TO_VARCHAR(PERIOD_CONSUMPTION - ALLOCATION, '999,999,990') || '.',
    'The order form lets Snowflake invoice an installment on the earlier of its '
      || 'scheduled date or the date consumption exceeds it, and to pull forward '
      || 'later invoices. Expect the next invoice sooner than the calendar implies. '
      || 'This is accelerated billing, not an overage charge.',
    PERIOD_BURN_PCT
  FROM enriched
  WHERE PULL_FORWARD_TRIGGERED = TRUE

  UNION ALL

  SELECT
    'CAPACITY_EXHAUSTION',
    'Capacity projected to run out before term end',
    IFF(DAYS_TO_EXHAUSTION <= 60, 'CRITICAL', 'WARNING'), 3,
    DAYS_TO_EXHAUSTION, EXHAUSTION_DATE,
    CURRENCY || ' ' || TO_VARCHAR(POOLED_REMAINING, '999,999,990')
      || ' of capacity remains. At the ' || RATE_BASIS || ' of '
      || CURRENCY || ' ' || TO_VARCHAR(RATE_PER_DAY, '999,999,990')
      || '/day it is exhausted on ' || TO_VARCHAR(EXHAUSTION_DATE, 'YYYY-MM-DD')
      || ', ' || TO_VARCHAR(DATEDIFF(day, EXHAUSTION_DATE, TERM_END))
      || ' days before the term ends.',
    'Plan an Additional Capacity Order before this date. Bought while still within '
      || 'capacity it carries the same negotiated discount; bought after, it does not.',
    DAYS_TO_EXHAUSTION
  FROM enriched
  WHERE DAYS_TO_EXHAUSTION IS NOT NULL
    AND EXHAUSTION_DATE < TERM_END
    AND DAYS_OF_HISTORY >= 14

  UNION ALL

  SELECT
    'PRICE_CLIFF',
    'Credit price rises when capacity is exhausted',
    'WARNING', 4,
    DAYS_TO_EXHAUSTION, EXHAUSTION_DATE,
    'After capacity is exhausted, usage converts to On Demand and the '
      || TO_VARCHAR(PRICE_CLIFF_PCT, '990.0') || '% credit discount no longer applies: '
      || CURRENCY || ' ' || TO_VARCHAR(CAPACITY_CREDIT_PRICE, '990.00') || ' becomes '
      || CURRENCY || ' ' || TO_VARCHAR(ON_DEMAND_CREDIT_PRICE, '990.00')
      || ' per credit. Projected exposure through term end is about '
      || CURRENCY || ' '
      || TO_VARCHAR(ROUND(GREATEST(DATEDIFF(day, EXHAUSTION_DATE, TERM_END), 0)
                          * RATE_PER_DAY * (PRICE_CLIFF_PCT / 100), 0), '999,999,990') || '.',
    'This increase is easy to miss because it appears as higher unit cost rather '
      || 'than a separate charge. Purchasing additional capacity before exhaustion '
      || 'avoids it entirely.',
    PRICE_CLIFF_PCT
  FROM enriched
  WHERE DAYS_TO_EXHAUSTION IS NOT NULL
    AND EXHAUSTION_DATE < TERM_END
    AND PRICE_CLIFF_PCT > 0
    AND DAYS_OF_HISTORY >= 14

  UNION ALL

  SELECT
    'IN_OVERAGE',
    'Capacity is already exhausted',
    'CRITICAL', 0,
    0, CURRENT_DATE(),
    'Cumulative consumption of ' || CURRENCY || ' '
      || TO_VARCHAR(CUM_CONSUMPTION, '999,999,990') || ' has passed the '
      || TO_VARCHAR(TOTAL_CAPACITY, '999,999,990') || ' capacity purchase by '
      || TO_VARCHAR(CUM_CONSUMPTION - TOTAL_CAPACITY, '999,999,990')
      || '. Usage is now billed On Demand at undiscounted rates, monthly in arrears.',
    'Purchasing additional capacity restores the negotiated discount on future '
      || 'consumption. Verify this against your latest invoice, and confirm the '
      || 'opening balance in Settings is correct.',
    TERM_BURN_PCT
  FROM enriched
  WHERE IS_IN_OVERAGE = TRUE
)
SELECT
  w.WARNING_CODE, w.WARNING_TITLE, w.SEVERITY, w.SORT_ORDER,
  w.DAYS_UNTIL, w.IMPACT_DATE, w.MESSAGE, w.RECOMMENDATION, w.METRIC_VALUE,
  e.CONTRACT_NUMBER, e.CURRENCY, e.RATE_BASIS, e.DAYS_OF_HISTORY,

  IFF(e.DAYS_OF_HISTORY < 60, TRUE, FALSE) AS IS_LOW_CONFIDENCE,
  e.DATA_COVERAGE AS CURRENT_PERIOD_COVERAGE,
  CURRENT_TIMESTAMP() AS BUILT_AT
FROM w CROSS JOIN enriched e;
create or replace view SF360.CURATED.FCT_THRESHOLD_STATUS(
	THRESHOLD_ID,
	SCOPE,
	THRESHOLD_PCT,
	LABEL,
	SEVERITY,
	NOTIFY_EMAIL,
	CURRENCY,
	PERIOD_LABEL,
	BASIS_AMOUNT,
	ACTUAL_AMOUNT,
	CURRENT_PCT,
	PROJECTED_PCT,
	HORIZON_DATE,
	THRESHOLD_AMOUNT,
	STATUS,
	DAYS_UNTIL_BREACH,
	BUILT_AT
) COMMENT='Evaluates each enabled threshold against both current and projected position. STATUS is OK, FORECAST_BREACH or BREACHED, so a threshold can warn before it is crossed rather than only after.'
 as
WITH pos AS (
  SELECT
    MAX(IFF(IS_CURRENT_PERIOD, PERIOD_LABEL,      NULL)) AS PERIOD_LABEL,
    MAX(IFF(IS_CURRENT_PERIOD, PERIOD_END,        NULL)) AS PERIOD_END,
    MAX(IFF(IS_CURRENT_PERIOD, ALLOCATION,        NULL)) AS ALLOCATION,
    MAX(IFF(IS_CURRENT_PERIOD, CONSUMPTION,       NULL)) AS PERIOD_CONSUMPTION,
    MAX(IFF(IS_CURRENT_PERIOD, PERIOD_BURN_PCT,   NULL)) AS PERIOD_PCT,
    MAX(IFF(IS_CURRENT_PERIOD, PROJECTED_PERIOD_BURN_PCT, NULL)) AS PERIOD_PCT_PROJ,
    MAX(IFF(IS_CURRENT_PERIOD, CUM_CONSUMPTION,   NULL)) AS CUM_CONSUMPTION,
    MAX(IFF(IS_CURRENT_PERIOD, TERM_BURN_PCT,     NULL)) AS TERM_PCT,
    MAX(TOTAL_CAPACITY) AS TOTAL_CAPACITY,
    MAX(TERM_END)       AS TERM_END,
    MAX(CURRENCY)       AS CURRENCY
  FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION
),
rate AS (
  SELECT COALESCE(
           MAX(IFF(METHOD='NATIVE_FORECAST_FLOORED', PROJECTED_RATE_PER_DAY, NULL)),
           MAX(IFF(METHOD='RUN_RATE_30D',            PROJECTED_RATE_PER_DAY, NULL))
         ) AS RATE_PER_DAY
  FROM SF360.CURATED.FCT_CONTRACT_PROJECTION
),
proj AS (
  SELECT p.*, r.RATE_PER_DAY,

    ROUND((p.CUM_CONSUMPTION
           + GREATEST(DATEDIFF(day, CURRENT_DATE(), p.TERM_END),0) * r.RATE_PER_DAY)
          / NULLIF(p.TOTAL_CAPACITY,0) * 100, 2) AS TERM_PCT_PROJ
  FROM pos p CROSS JOIN rate r
),
ev AS (
  SELECT
    t.THRESHOLD_ID, t.SCOPE, t.THRESHOLD_PCT, t.LABEL, t.SEVERITY, t.NOTIFY_EMAIL,
    p.CURRENCY, p.PERIOD_LABEL, p.PERIOD_END, p.TERM_END,
    CASE t.SCOPE WHEN 'PERIOD' THEN p.PERIOD_PCT      ELSE p.TERM_PCT      END AS CURRENT_PCT,
    CASE t.SCOPE WHEN 'PERIOD' THEN p.PERIOD_PCT_PROJ ELSE p.TERM_PCT_PROJ END AS PROJECTED_PCT,
    CASE t.SCOPE WHEN 'PERIOD' THEN p.ALLOCATION      ELSE p.TOTAL_CAPACITY END AS BASIS_AMOUNT,
    CASE t.SCOPE WHEN 'PERIOD' THEN p.PERIOD_CONSUMPTION ELSE p.CUM_CONSUMPTION END AS ACTUAL_AMOUNT,
    CASE t.SCOPE WHEN 'PERIOD' THEN p.PERIOD_END      ELSE p.TERM_END       END AS HORIZON_DATE,
    p.RATE_PER_DAY
  FROM SF360.CONFIG.ALERT_THRESHOLDS t
  CROSS JOIN proj p
  WHERE t.IS_ENABLED
)
SELECT
  THRESHOLD_ID, SCOPE, THRESHOLD_PCT, LABEL, SEVERITY, NOTIFY_EMAIL,
  CURRENCY, PERIOD_LABEL, BASIS_AMOUNT, ACTUAL_AMOUNT,
  CURRENT_PCT, PROJECTED_PCT, HORIZON_DATE,
  ROUND(BASIS_AMOUNT * THRESHOLD_PCT / 100, 2) AS THRESHOLD_AMOUNT,
  CASE
    WHEN CURRENT_PCT   >= THRESHOLD_PCT THEN 'BREACHED'
    WHEN PROJECTED_PCT >= THRESHOLD_PCT THEN 'FORECAST_BREACH'
    ELSE 'OK'
  END AS STATUS,

  CASE
    WHEN CURRENT_PCT >= THRESHOLD_PCT THEN 0
    WHEN RATE_PER_DAY > 0
      THEN CEIL((BASIS_AMOUNT * THRESHOLD_PCT / 100 - ACTUAL_AMOUNT) / RATE_PER_DAY)
    ELSE NULL
  END AS DAYS_UNTIL_BREACH,
  CURRENT_TIMESTAMP() AS BUILT_AT
FROM ev;
create or replace view SF360.CURATED.VW_VERIFICATION(
	CHK,
	CHECK_NAME,
	ACTUAL,
	EXPECTED,
	RESULT
) as

SELECT 1 AS CHK, 'G1 dim_account key uniqueness' AS CHECK_NAME,
       (COUNT(*) - COUNT(DISTINCT ACCOUNT_KEY))::VARCHAR AS ACTUAL, '0' AS EXPECTED,
       IFF(COUNT(*) = COUNT(DISTINCT ACCOUNT_KEY), 'PASS','FAIL') AS RESULT
FROM SF360.CURATED.DIM_ACCOUNT
UNION ALL

SELECT 2, 'G1b no join fanout currency to dim',
       (SELECT COUNT(*) FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY u
          JOIN SF360.CURATED.DIM_ACCOUNT d
            ON d.ACCOUNT_LOCATOR=u.ACCOUNT_LOCATOR AND d.REGION=u.REGION)::VARCHAR,
       (SELECT COUNT(*) FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY)::VARCHAR,
       IFF((SELECT COUNT(*) FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY u
              JOIN SF360.CURATED.DIM_ACCOUNT d
                ON d.ACCOUNT_LOCATOR=u.ACCOUNT_LOCATOR AND d.REGION=u.REGION)
           = (SELECT COUNT(*) FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY), 'PASS','FAIL')
UNION ALL

SELECT 3, 'G2 all in-scope accounts have rates',
       (SELECT COUNT_IF(PRICE_PER_PLATFORM_CREDIT IS NULL) FROM SF360.CONFIG.SUBSCRIPTION)::VARCHAR, '0',
       IFF((SELECT COUNT_IF(PRICE_PER_PLATFORM_CREDIT IS NULL) FROM SF360.CONFIG.SUBSCRIPTION)=0,'PASS','FAIL')
UNION ALL

SELECT 4, 'G2b editions resolve distinct rates',
       (SELECT COUNT(DISTINCT PRICE_PER_PLATFORM_CREDIT) FROM SF360.CONFIG.SUBSCRIPTION)::VARCHAR, '>1',
       IFF((SELECT COUNT(DISTINCT PRICE_PER_PLATFORM_CREDIT) FROM SF360.CONFIG.SUBSCRIPTION)>1,'PASS','FAIL')
UNION ALL

SELECT 5, 'G4 adjustments separated from usage',
       (SELECT COUNT_IF(USAGE_IN_CURRENCY <> 0 AND ADJUSTMENT_IN_CURRENCY <> 0)
          FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY)::VARCHAR, '0',
       IFF((SELECT COUNT_IF(USAGE_IN_CURRENCY <> 0 AND ADJUSTMENT_IN_CURRENCY <> 0)
              FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY)=0,'PASS','FAIL')
UNION ALL

SELECT 6, 'G6 single currency in scope',
       (SELECT COUNT(DISTINCT CURRENCY) FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY)::VARCHAR, '1',
       IFF((SELECT COUNT(DISTINCT CURRENCY) FROM SF360.LANDING.LND_ORG_CURRENCY_DAILY)=1,'PASS','WARN')
UNION ALL

SELECT 7, 'CLS org metering fully classified',
       (SELECT COUNT(*) FROM SF360.LANDING.LND_ORG_METERING_DAILY m
          LEFT JOIN SF360.CURATED.DIM_SERVICE_TYPE d ON d.SERVICE_TYPE=m.SERVICE_TYPE
          WHERE d.SERVICE_TYPE IS NULL)::VARCHAR, '0',
       IFF((SELECT COUNT(*) FROM SF360.LANDING.LND_ORG_METERING_DAILY m
              LEFT JOIN SF360.CURATED.DIM_SERVICE_TYPE d ON d.SERVICE_TYPE=m.SERVICE_TYPE
              WHERE d.SERVICE_TYPE IS NULL)=0,'PASS','FAIL')
UNION ALL

SELECT 8, 'CLS platform plus AI equals total',
       ROUND((SELECT SUM(CREDITS_BILLED) FROM SF360.CURATED.FCT_DAILY_CREDITS)
             - (SELECT SUM(CREDITS_BILLED) FROM SF360.CURATED.FCT_DAILY_CREDITS
                WHERE CREDIT_CLASS IN ('PLATFORM','AI')), 6)::VARCHAR, '0',
       IFF(ABS((SELECT SUM(CREDITS_BILLED) FROM SF360.CURATED.FCT_DAILY_CREDITS)
               - (SELECT SUM(CREDITS_BILLED) FROM SF360.CURATED.FCT_DAILY_CREDITS
                  WHERE CREDIT_CLASS IN ('PLATFORM','AI'))) < 0.000001,'PASS','FAIL')
UNION ALL

SELECT 9, 'FC no negative forecast or bound',
       (SELECT COUNT_IF(FORECASTED_VALUE < 0 OR LOWER_BOUND < 0)
          FROM SF360.CURATED.FCT_ANOMALY_DAILY)::VARCHAR, '0',
       IFF((SELECT COUNT_IF(FORECASTED_VALUE < 0 OR LOWER_BOUND < 0)
              FROM SF360.CURATED.FCT_ANOMALY_DAILY)=0,'PASS','FAIL')
UNION ALL
SELECT 10, 'FC no negative projection rate',
       (SELECT COUNT_IF(PROJECTED_RATE_PER_DAY < 0 OR PROJECTED_OVERAGE < 0)
          FROM SF360.CURATED.FCT_CONTRACT_PROJECTION)::VARCHAR, '0',
       IFF((SELECT COUNT_IF(PROJECTED_RATE_PER_DAY < 0 OR PROJECTED_OVERAGE < 0)
              FROM SF360.CURATED.FCT_CONTRACT_PROJECTION)=0,'PASS','FAIL')
UNION ALL

SELECT 11, 'G7 in-scope accounts missing usage',
       (SELECT COUNT(*) FROM SF360.CURATED.DIM_ACCOUNT d
          WHERE d.IS_IN_SCOPE
            AND NOT EXISTS (SELECT 1 FROM SF360.CURATED.FCT_DAILY_CURRENCY f
                            WHERE f.ACCOUNT_KEY = d.ACCOUNT_KEY))::VARCHAR, '0',
       IFF((SELECT COUNT(*) FROM SF360.CURATED.DIM_ACCOUNT d
              WHERE d.IS_IN_SCOPE
                AND NOT EXISTS (SELECT 1 FROM SF360.CURATED.FCT_DAILY_CURRENCY f
                                WHERE f.ACCOUNT_KEY = d.ACCOUNT_KEY))=0,'PASS','WARN')
UNION ALL

SELECT 12, 'CT exactly one active contract',
       (SELECT COUNT(*) FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE AND VALID_TO IS NULL)::VARCHAR, '1',
       IFF((SELECT COUNT(*) FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE AND VALID_TO IS NULL)=1,'PASS','FAIL')
UNION ALL

SELECT 13, 'FY fiscal labels follow the Feb-1 fiscal rule',
       (SELECT COUNT_IF(FISCAL_QUARTER_LABEL <> (CASE WHEN MONTH(DATE_UTC) >= 2 THEN YEAR(DATE_UTC) ELSE YEAR(DATE_UTC)-1 END) || '-Q' || (FLOOR(MOD(MONTH(DATE_UTC)-2+12,12)/3)+1))::VARCHAR
          || ' mismatched of ' || COUNT(*)::VARCHAR || ' dates' FROM SF360.CURATED.DIM_DATE),
       '0 mismatched, at least 1 date',
       IFF((SELECT COUNT(*) FROM SF360.CURATED.DIM_DATE) > 0
           AND COALESCE((SELECT COUNT_IF(FISCAL_QUARTER_LABEL <> (CASE WHEN MONTH(DATE_UTC) >= 2 THEN YEAR(DATE_UTC) ELSE YEAR(DATE_UTC)-1 END) || '-Q' || (FLOOR(MOD(MONTH(DATE_UTC)-2+12,12)/3)+1)) FROM SF360.CURATED.DIM_DATE), 1) = 0,
           'PASS','FAIL')
UNION ALL


SELECT 14, 'BP1 allocations sum to capacity',
       (SELECT TO_VARCHAR(ROUND(SUM(ALLOCATION),2)) FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION),
       (SELECT TO_VARCHAR(ROUND(MAX(TOTAL_CAPACITY),2)) FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION),
       IFF((SELECT ABS(SUM(ALLOCATION) - MAX(TOTAL_CAPACITY))
              FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION) <= 1.00, 'PASS', 'FAIL')
UNION ALL

SELECT 15, 'BP2 periods contiguous',
       (SELECT COUNT(*)::VARCHAR FROM (
          SELECT PERIOD_END, LEAD(PERIOD_START) OVER (ORDER BY PERIOD_SEQ) AS NXT
          FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION)
        WHERE NXT IS NOT NULL AND NXT <> DATEADD(day,1,PERIOD_END)), '0',
       IFF((SELECT COUNT(*) FROM (
              SELECT PERIOD_END, LEAD(PERIOD_START) OVER (ORDER BY PERIOD_SEQ) AS NXT
              FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION)
            WHERE NXT IS NOT NULL AND NXT <> DATEADD(day,1,PERIOD_END))=0,'PASS','FAIL')
UNION ALL

SELECT 16, 'BP3 period count matches cadence',
       (SELECT MAX(PERIOD_COUNT)::VARCHAR FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION),
       (SELECT TO_VARCHAR(CEIL(MAX(TERM_LENGTH_MONTHS)
              / NULLIF(SF360.ORDERFORM.FN_CADENCE_MONTHS(MAX(BILLING_FREQUENCY)),0)))
          FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE),
       IFF((SELECT MAX(PERIOD_COUNT) FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION)
           = (SELECT CEIL(MAX(TERM_LENGTH_MONTHS)
                / NULLIF(SF360.ORDERFORM.FN_CADENCE_MONTHS(MAX(BILLING_FREQUENCY)),0))
              FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE), 'PASS','FAIL')
UNION ALL


SELECT 17, 'BP4 pooled remaining reconciles',
       (SELECT TO_VARCHAR(ROUND(MAX(ABS(TOTAL_CAPACITY - CUM_CONSUMPTION - POOLED_REMAINING)),2))
          FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION), '0',
       IFF((SELECT MAX(ABS(TOTAL_CAPACITY - CUM_CONSUMPTION - POOLED_REMAINING))
              FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION) <= 0.02, 'PASS','FAIL')
UNION ALL

SELECT 18, 'BP5 one current period',
       (SELECT COUNT_IF(IS_CURRENT_PERIOD)::VARCHAR FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION), '1',
       IFF((SELECT COUNT_IF(IS_CURRENT_PERIOD) FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION)=1,
           'PASS','WARN')
UNION ALL


SELECT 19, 'BP6 unmeasurable periods are null',
       (SELECT COUNT_IF(DATA_COVERAGE='NO_DATA' AND CONSUMPTION IS NOT NULL)::VARCHAR
          FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION), '0',
       IFF((SELECT COUNT_IF(DATA_COVERAGE='NO_DATA' AND CONSUMPTION IS NOT NULL)
              FROM SF360.CURATED.FCT_BILLING_PERIOD_POSITION)=0,'PASS','FAIL')
UNION ALL


SELECT 20, 'TH1 warnings have lead time',
       (SELECT COUNT_IF(DAYS_UNTIL IS NULL)::VARCHAR FROM SF360.CURATED.FCT_CAPACITY_WARNING), '0',
       IFF((SELECT COUNT_IF(DAYS_UNTIL IS NULL) FROM SF360.CURATED.FCT_CAPACITY_WARNING)=0,
           'PASS','FAIL')
UNION ALL




SELECT 21, 'TH2 thresholds all evaluated',
       (SELECT COALESCE(COUNT_IF(STATUS NOT IN ('OK','FORECAST_BREACH','BREACHED')),0)::VARCHAR
          FROM SF360.CURATED.FCT_THRESHOLD_STATUS), '0',
       IFF((SELECT COALESCE(COUNT_IF(STATUS NOT IN ('OK','FORECAST_BREACH','BREACHED')),0)
              FROM SF360.CURATED.FCT_THRESHOLD_STATUS)=0,'PASS','FAIL')
UNION ALL

SELECT 22, 'OF1 extracted contract has provenance',
       (SELECT COUNT_IF(CONTRACT_SOURCE='ORDER_FORM_EXTRACTED' AND SOURCE_UPLOAD_ID IS NULL)::VARCHAR
          FROM SF360.CONFIG.CONTRACT), '0',
       IFF((SELECT COUNT_IF(CONTRACT_SOURCE='ORDER_FORM_EXTRACTED' AND SOURCE_UPLOAD_ID IS NULL)
              FROM SF360.CONFIG.CONTRACT)=0,'PASS','FAIL')
UNION ALL


SELECT 23, 'OF2 on demand price >= contract price',
       (SELECT COUNT_IF(ON_DEMAND_CREDIT_PRICE < CAPACITY_CREDIT_PRICE)::VARCHAR
          FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE), '0',
       IFF((SELECT COUNT_IF(ON_DEMAND_CREDIT_PRICE < CAPACITY_CREDIT_PRICE)
              FROM SF360.CONFIG.CONTRACT WHERE IS_ACTIVE)=0,'PASS','FAIL');
CREATE OR REPLACE PROCEDURE SF360.CURATED.SP_REFRESH_CURATED()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
  ALTER SESSION SET TIMEZONE = ''UTC'';
  -- Dimensions first
  ALTER DYNAMIC TABLE SF360.CURATED.DIM_ACCOUNT REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.DIM_SERVICE_TYPE REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.DIM_DATE REFRESH;
  -- Rates before anything that prices
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_RATE_EFFECTIVE REFRESH;
  -- Facts
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_DAILY_CREDITS REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_DAILY_CURRENCY REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_QUERY_ATTRIBUTION REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_ANOMALY_DAILY REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_OPTIMIZATION_OPPORTUNITY REFRESH;
  -- Contract position depends on currency and dim_date; projection depends on position
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_CONTRACT_POSITION REFRESH;
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_CONTRACT_PROJECTION REFRESH;
  -- Freshness last so it records the completed state
  ALTER DYNAMIC TABLE SF360.CURATED.FCT_FRESHNESS REFRESH;
  RETURN ''SP_REFRESH_CURATED complete'';
END;
';
