-- Snowflake360 :: LANDING schema, scripted from the live account.
--
-- Captured as a baseline because these objects were created ad hoc during
-- development and their definitions existed only inside the account. This file
-- is the reproducible record; the numbered files in sql/ remain the source of
-- truth for anything created after it.
--
-- Originally scripted from a live SF360 deployment, then hand-corrected.
--
-- Four tables that this file used to build were removed after an audit found that
-- nothing read them: LND_ORG_CONTRACT_ITEMS, LND_STORAGE_DAILY,
-- LND_WAREHOUSE_EVENTS_DAILY and LND_WAREHOUSE_LOAD_DAILY. They were built on
-- every nightly run and granted to SF360_APP_ROLE, but no page, no curated object
-- and no procedure referenced any of them -- they were landed during development
-- for panels that were ultimately built from other sources. Storage in particular
-- still reaches the app: it arrives as SERVICE_TYPE 'STORAGE' through
-- LND_ORG_CURRENCY_DAILY into FCT_DAILY_CURRENCY, which is what the Consumption
-- and Usage pages read.
--
-- CREATE OR REPLACE is correct in this schema, unlike in CONFIG. Everything here
-- is a projection of SNOWFLAKE.ACCOUNT_USAGE / ORGANIZATION_USAGE and is rebuilt
-- in full nightly, because those views back-fill late-arriving rows and a
-- trailing-window incremental load would silently miss them.

USE DATABASE SF360;

create or replace schema SF360.LANDING COMMENT='Sole consumer of SNOWFLAKE.ACCOUNT_USAGE. Task-driven CTAS; exists because dynamic tables cannot read shared secure views.';

create or replace TRANSIENT TABLE SF360.LANDING.LND_ACCT_ANOMALIES (
	ACCOUNT_NAME VARCHAR(16777216),
	ANOMALY_DATE DATE,
	ANOMALY_ID VARCHAR(16777216),
	IS_ANOMALY BOOLEAN,
	ACTUAL_VALUE NUMBER(38,2),
	FORECASTED_VALUE_FLOORED NUMBER(38,2),
	FORECASTED_VALUE_RAW NUMBER(38,2),
	LOWER_BOUND_FLOORED NUMBER(38,2),
	UPPER_BOUND NUMBER(38,2),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_AI_USAGE_DAILY (
	ACCOUNT_NAME VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	FEATURE VARCHAR(19),
	SUB_FEATURE VARCHAR(16777216),
	MODEL_NAME VARCHAR(16777216),
	USER_NAME VARCHAR(16777216),
	CREDITS NUMBER(38,9),
	TOKENS NUMBER(38,0),
	EVENT_COUNT NUMBER(18,0),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_DATA_TRANSFER_DAILY (
	ACCOUNT_NAME VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	TRANSFER_TYPE VARCHAR(16777216),
	SOURCE_CLOUD VARCHAR(16777216),
	SOURCE_REGION VARCHAR(16777216),
	TARGET_CLOUD VARCHAR(16777216),
	TARGET_REGION VARCHAR(16777216),
	BYTES_TRANSFERRED FLOAT,
	TB_TRANSFERRED FLOAT,
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_METERING_DAILY (
	ACCOUNT_NAME VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	SERVICE_TYPE VARCHAR(16777216),
	CREDITS_USED_COMPUTE NUMBER(38,9),
	CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
	CREDITS_USED NUMBER(38,9),
	CREDITS_ADJUSTMENT_CLOUD_SERVICES NUMBER(38,10),
	CREDITS_BILLED NUMBER(38,10),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_ACCOUNTS (
	ORGANIZATION_NAME VARCHAR(16777216),
	ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_LOCATOR VARCHAR(16777216),
	REGION VARCHAR(16777216),
	REGION_GROUP VARCHAR(16777216),
	EDITION VARCHAR(16777216),
	CREATED_ON TIMESTAMP_LTZ(6),
	DELETED_ON TIMESTAMP_LTZ(6),
	MOVED_ON TIMESTAMP_LTZ(6),
	ALTERED_ON TIMESTAMP_LTZ(6),
	IS_ORG_ADMIN BOOLEAN,
	IS_LOCKED BOOLEAN,
	IS_MANAGED BOOLEAN,
	MANAGED_ACCOUNTS NUMBER(18,0),
	PARENT_ACCOUNT VARCHAR(16777216),
	ACCOUNT_URL VARCHAR(16777216),
	COMMENT VARCHAR(16777216),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_ANOMALIES (
	ANOMALY_DATE DATE,
	ANOMALY_ID VARCHAR(16777216),
	IS_ANOMALY BOOLEAN,
	ORGANIZATION_NAME VARCHAR(16777216),
	ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_LOCATOR VARCHAR(16777216),
	REGION VARCHAR(16777216),
	ACCOUNT_KEY VARCHAR(16777216),
	CURRENCY VARCHAR(16777216),
	ACTUAL_VALUE NUMBER(38,2),
	FORECASTED_VALUE_FLOORED NUMBER(38,2),
	FORECASTED_VALUE_RAW NUMBER(38,2),
	LOWER_BOUND_FLOORED NUMBER(38,2),
	UPPER_BOUND NUMBER(38,2),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_CURRENCY_DAILY (
	ORGANIZATION_NAME VARCHAR(16777216),
	CONTRACT_NUMBER NUMBER(38,0),
	ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_LOCATOR VARCHAR(16777216),
	REGION VARCHAR(16777216),
	ACCOUNT_KEY VARCHAR(16777216),
	SERVICE_LEVEL VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	SERVICE_TYPE VARCHAR(16777216),
	USAGE_TYPE VARCHAR(16777216),
	RATING_TYPE VARCHAR(16777216),
	BILLING_TYPE VARCHAR(16777216),
	BALANCE_SOURCE VARCHAR(16777216),
	CURRENCY VARCHAR(16777216),
	IS_ADJUSTMENT BOOLEAN,
	USAGE_QTY NUMBER(38,3),
	USAGE_IN_CURRENCY NUMBER(38,2),
	ADJUSTMENT_IN_CURRENCY NUMBER(38,2),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_METERING_DAILY (
	ORGANIZATION_NAME VARCHAR(16777216),
	ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_LOCATOR VARCHAR(16777216),
	REGION VARCHAR(16777216),
	ACCOUNT_KEY VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	SERVICE_TYPE VARCHAR(16777216),
	CREDITS_USED_COMPUTE NUMBER(38,9),
	CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
	CREDITS_USED NUMBER(38,9),
	CREDITS_ADJUSTMENT_CLOUD_SERVICES NUMBER(38,10),
	CREDITS_BILLED NUMBER(38,10),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_RATE_SHEET (
	RATE_DATE DATE,
	ORGANIZATION_NAME VARCHAR(16777216),
	CONTRACT_NUMBER NUMBER(38,0),
	ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_LOCATOR VARCHAR(16777216),
	REGION VARCHAR(16777216),
	ACCOUNT_KEY VARCHAR(16777216),
	SERVICE_LEVEL VARCHAR(16777216),
	USAGE_TYPE VARCHAR(16777216),
	SERVICE_TYPE VARCHAR(16777216),
	RATING_TYPE VARCHAR(16777216),
	BILLING_TYPE VARCHAR(16777216),
	CURRENCY VARCHAR(16777216),
	EFFECTIVE_RATE NUMBER(38,2),
	IS_ADJUSTMENT BOOLEAN,
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_REMAINING_BALANCE (
	ORGANIZATION_NAME VARCHAR(16777216),
	CONTRACT_NUMBER NUMBER(38,0),
	BALANCE_DATE DATE,
	CURRENCY VARCHAR(16777216),
	FREE_USAGE_BALANCE NUMBER(38,2),
	CAPACITY_BALANCE NUMBER(38,2),
	ON_DEMAND_CONSUMPTION_BALANCE NUMBER(38,2),
	ROLLOVER_BALANCE NUMBER(38,2),
	MARKETPLACE_CAPACITY_DRAWDOWN_BALANCE NUMBER(38,2),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_ORG_SERVICE_TYPES (
	SERVICE_TYPE VARCHAR(16777216),
	RATING_TYPE VARCHAR(16777216),
	RATE_ROWS NUMBER(18,0),
	LAST_SEEN DATE,
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_QUERY_ATTRIBUTION (
	ACCOUNT_NAME VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	QUERY_ID VARCHAR(16777216),
	PARENT_QUERY_ID VARCHAR(16777216),
	ROOT_QUERY_ID VARCHAR(16777216),
	WAREHOUSE_ID NUMBER(38,0),
	WAREHOUSE_NAME VARCHAR(16777216),
	USER_NAME VARCHAR(16777216),
	ROLE_NAME VARCHAR(16777216),
	DATABASE_NAME VARCHAR(16777216),
	SCHEMA_NAME VARCHAR(16777216),
	QUERY_TYPE VARCHAR(16777216),
	EXECUTION_STATUS VARCHAR(16777216),
	WAREHOUSE_SIZE VARCHAR(16777216),
	QUERY_TAG VARCHAR(16777216),
	START_TIME TIMESTAMP_LTZ(3),
	END_TIME TIMESTAMP_LTZ(3),
	CREDITS_ATTRIBUTED_COMPUTE FLOAT,
	CREDITS_USED_QUERY_ACCELERATION FLOAT,
	BYTES_SCANNED NUMBER(38,0),
	TOTAL_ELAPSED_TIME NUMBER(38,0),
	EXECUTION_TIME NUMBER(38,0),
	QUEUED_OVERLOAD_TIME NUMBER(38,0),
	BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER(38,0),
	BYTES_SPILLED_TO_REMOTE_STORAGE NUMBER(38,0),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_QUERY_DAILY (
	ACCOUNT_NAME VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	WAREHOUSE_NAME VARCHAR(16777216),
	WAREHOUSE_SIZE VARCHAR(16777216),
	USER_NAME VARCHAR(16777216),
	ROLE_NAME VARCHAR(16777216),
	QUERY_TYPE VARCHAR(16777216),
	EXECUTION_STATUS VARCHAR(16777216),
	QUERY_COUNT NUMBER(18,0),
	QUERY_COUNT_SUCCESS NUMBER(13,0),
	BYTES_SCANNED NUMBER(38,0),
	ROWS_PRODUCED NUMBER(38,0),
	TOTAL_ELAPSED_MS NUMBER(38,0),
	EXECUTION_MS NUMBER(38,0),
	QUEUED_OVERLOAD_MS NUMBER(38,0),
	COMPILATION_MS NUMBER(38,0),
	SPILL_LOCAL_BYTES NUMBER(38,0),
	SPILL_REMOTE_BYTES NUMBER(38,0),
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_QUERY_INSIGHTS (
	ACCOUNT_NAME VARCHAR(16777216),
	START_TIME TIMESTAMP_LTZ(9),
	END_TIME TIMESTAMP_LTZ(9),
	TOTAL_ELAPSED_TIME NUMBER(38,0),
	QUERY_ID VARCHAR(16777216),
	QUERY_HASH VARCHAR(16777216),
	QUERY_PARAMETERIZED_HASH VARCHAR(16777216),
	WAREHOUSE_ID NUMBER(38,0),
	WAREHOUSE_NAME VARCHAR(16777216),
	INSIGHT_INSTANCE_ID VARCHAR(16777216),
	INSIGHT_TYPE_ID VARCHAR(16777216),
	INSIGHT_TOPIC VARCHAR(16777216),
	IS_OPPORTUNITY BOOLEAN,
	MESSAGE OBJECT,
	SUGGESTIONS ARRAY,
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_SHARING_INVENTORY (
	ACCOUNT_NAME VARCHAR(16777216),
	OBJECT_KIND VARCHAR(16777216),
	OBJECT_NAME VARCHAR(16777216),
	OBJECT_DETAIL VARCHAR(16777216),
	OWNER_NAME VARCHAR(16777216),
	TARGET_ACCOUNTS VARCHAR(16777216),
	LISTING_GLOBAL_NAME VARCHAR(16777216),
	STATE VARCHAR(16777216),
	CREATED_DATE DATE,
	DELETED_DATE DATE,
	LOADED_AT TIMESTAMP_LTZ(9)
);
create or replace TRANSIENT TABLE SF360.LANDING.LND_WAREHOUSE_METERING (
	ACCOUNT_NAME VARCHAR(16777216),
	WAREHOUSE_ID NUMBER(38,0),
	WAREHOUSE_NAME VARCHAR(16777216),
	USAGE_DATE_UTC DATE,
	CREDITS_USED_COMPUTE NUMBER(38,9),
	CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
	CREDITS_USED NUMBER(38,9),
	METERING_HOURS NUMBER(18,0),
	LOADED_AT TIMESTAMP_LTZ(9)
);
CREATE OR REPLACE PROCEDURE SF360.LANDING.SP_REBUILD_LANDING()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
  retention NUMBER;
  msg VARCHAR DEFAULT '''';
BEGIN
  -- Docs mandate UTC for reconciling ACCOUNT_USAGE against ORGANIZATION_USAGE
  ALTER SESSION SET TIMEZONE = ''UTC'';
  SELECT TO_NUMBER(SETTING_VALUE) INTO :retention
    FROM SF360.CONFIG.SETTINGS WHERE SETTING_KEY = ''RETENTION_DAYS'';

  -- Org object inventory
  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_ACCOUNTS AS
    SELECT ORGANIZATION_NAME, ACCOUNT_NAME, ACCOUNT_LOCATOR, REGION, REGION_GROUP, EDITION,
           CREATED_ON, DELETED_ON, MOVED_ON, ALTERED_ON, IS_ORG_ADMIN, IS_LOCKED,
           IS_MANAGED, MANAGED_ACCOUNTS, PARENT_ACCOUNT, ACCOUNT_URL, COMMENT,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.ACCOUNTS;

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_SERVICE_TYPES AS
    SELECT SERVICE_TYPE, RATING_TYPE, COUNT(*) AS RATE_ROWS, MAX(DATE) AS LAST_SEEN,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.RATE_SHEET_DAILY
    WHERE DATE >= DATEADD(''day'', -90, CURRENT_DATE())
    GROUP BY SERVICE_TYPE, RATING_TYPE;

  msg := ''org inventory ok; '';

  -- Org scoped history. Bounded time, explicit columns, account filter per docs.
  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_RATE_SHEET AS
    WITH scope AS (SELECT ACCOUNT_NAME FROM SF360.CONFIG.ACCOUNT_SCOPE WHERE IS_INCLUDED),
         se AS (SELECT (COUNT(*)=0) AS ALL_ACCT FROM scope)
    SELECT r.DATE AS RATE_DATE, r.ORGANIZATION_NAME, r.CONTRACT_NUMBER, r.ACCOUNT_NAME,
           r.ACCOUNT_LOCATOR, r.REGION, r.ACCOUNT_LOCATOR || ''|'' || r.REGION AS ACCOUNT_KEY,
           r.SERVICE_LEVEL, r.USAGE_TYPE, r.SERVICE_TYPE, r.RATING_TYPE, r.BILLING_TYPE,
           r.CURRENCY, r.EFFECTIVE_RATE, r.IS_ADJUSTMENT, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.RATE_SHEET_DAILY r CROSS JOIN se
    WHERE r.DATE >= DATEADD(''day'', -:retention, CURRENT_DATE())
      AND (se.ALL_ACCT OR r.ACCOUNT_NAME IN (SELECT ACCOUNT_NAME FROM scope));

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_CURRENCY_DAILY AS
    WITH scope AS (SELECT ACCOUNT_NAME FROM SF360.CONFIG.ACCOUNT_SCOPE WHERE IS_INCLUDED),
         se AS (SELECT (COUNT(*)=0) AS ALL_ACCT FROM scope)
    SELECT u.ORGANIZATION_NAME, u.CONTRACT_NUMBER, u.ACCOUNT_NAME, u.ACCOUNT_LOCATOR, u.REGION,
           u.ACCOUNT_LOCATOR || ''|'' || u.REGION AS ACCOUNT_KEY, u.SERVICE_LEVEL,
           u.USAGE_DATE AS USAGE_DATE_UTC, u.SERVICE_TYPE, u.USAGE_TYPE, u.RATING_TYPE,
           u.BILLING_TYPE, u.BALANCE_SOURCE, u.CURRENCY, u.IS_ADJUSTMENT,
           CASE WHEN u.IS_ADJUSTMENT THEN 0 ELSE u.USAGE END             AS USAGE_QTY,
           CASE WHEN u.IS_ADJUSTMENT THEN 0 ELSE u.USAGE_IN_CURRENCY END AS USAGE_IN_CURRENCY,
           CASE WHEN u.IS_ADJUSTMENT THEN u.USAGE_IN_CURRENCY ELSE 0 END AS ADJUSTMENT_IN_CURRENCY,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY u CROSS JOIN se
    WHERE u.USAGE_DATE >= DATEADD(''day'', -:retention, CURRENT_DATE())
      AND (se.ALL_ACCT OR u.ACCOUNT_NAME IN (SELECT ACCOUNT_NAME FROM scope));

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_METERING_DAILY AS
    WITH scope AS (SELECT ACCOUNT_NAME FROM SF360.CONFIG.ACCOUNT_SCOPE WHERE IS_INCLUDED),
         se AS (SELECT (COUNT(*)=0) AS ALL_ACCT FROM scope)
    SELECT m.ORGANIZATION_NAME, m.ACCOUNT_NAME, m.ACCOUNT_LOCATOR, m.REGION,
           m.ACCOUNT_LOCATOR || ''|'' || m.REGION AS ACCOUNT_KEY,
           m.USAGE_DATE AS USAGE_DATE_UTC, m.SERVICE_TYPE,
           SUM(m.CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
           SUM(m.CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
           SUM(m.CREDITS_USED) AS CREDITS_USED,
           SUM(m.CREDITS_ADJUSTMENT_CLOUD_SERVICES) AS CREDITS_ADJUSTMENT_CLOUD_SERVICES,
           SUM(m.CREDITS_BILLED) AS CREDITS_BILLED, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.METERING_DAILY_HISTORY m CROSS JOIN se
    WHERE m.USAGE_DATE >= DATEADD(''day'', -:retention, CURRENT_DATE())
      AND (se.ALL_ACCT OR m.ACCOUNT_NAME IN (SELECT ACCOUNT_NAME FROM scope))
    GROUP BY 1,2,3,4,5,6,7;

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_REMAINING_BALANCE AS
    SELECT ORGANIZATION_NAME, CONTRACT_NUMBER, DATE AS BALANCE_DATE, CURRENCY,
           FREE_USAGE_BALANCE, CAPACITY_BALANCE, ON_DEMAND_CONSUMPTION_BALANCE,
           ROLLOVER_BALANCE, MARKETPLACE_CAPACITY_DRAWDOWN_BALANCE,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.REMAINING_BALANCE_DAILY
    WHERE DATE >= DATEADD(''day'', -:retention, CURRENT_DATE());

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ORG_ANOMALIES AS
    WITH scope AS (SELECT ACCOUNT_NAME FROM SF360.CONFIG.ACCOUNT_SCOPE WHERE IS_INCLUDED),
         se AS (SELECT (COUNT(*)=0) AS ALL_ACCT FROM scope)
    SELECT a.DATE AS ANOMALY_DATE, a.ANOMALY_ID, a.IS_ANOMALY, a.ORGANIZATION_NAME,
           a.ACCOUNT_NAME, a.ACCOUNT_LOCATOR, a.REGION,
           a.ACCOUNT_LOCATOR || ''|'' || a.REGION AS ACCOUNT_KEY, a.CURRENCY, a.ACTUAL_VALUE,
           GREATEST(a.FORECASTED_VALUE,0) AS FORECASTED_VALUE_FLOORED,
           a.FORECASTED_VALUE AS FORECASTED_VALUE_RAW,
           GREATEST(a.LOWER_BOUND,0) AS LOWER_BOUND_FLOORED, a.UPPER_BOUND,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ORGANIZATION_USAGE.ANOMALIES_IN_CURRENCY_DAILY a CROSS JOIN se
    WHERE a.DATE >= DATEADD(''day'', -:retention, CURRENT_DATE())
      AND (se.ALL_ACCT OR a.ACCOUNT_NAME IN (SELECT ACCOUNT_NAME FROM scope));

  msg := msg || ''org history ok; '';
  RETURN msg || ''SP_REBUILD_LANDING complete'';
END;
';
CREATE OR REPLACE PROCEDURE SF360.LANDING.SP_REBUILD_LANDING_ACCOUNT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
  retention NUMBER;
BEGIN
  ALTER SESSION SET TIMEZONE = ''UTC'';
  SELECT TO_NUMBER(SETTING_VALUE) INTO :retention
    FROM SF360.CONFIG.SETTINGS WHERE SETTING_KEY = ''RETENTION_DAYS'';

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_METERING_DAILY AS
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, USAGE_DATE AS USAGE_DATE_UTC, SERVICE_TYPE,
           SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
           SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
           SUM(CREDITS_USED) AS CREDITS_USED,
           SUM(CREDITS_ADJUSTMENT_CLOUD_SERVICES) AS CREDITS_ADJUSTMENT_CLOUD_SERVICES,
           SUM(CREDITS_BILLED) AS CREDITS_BILLED, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
    WHERE USAGE_DATE >= DATEADD(''day'', -:retention, CURRENT_DATE())
    GROUP BY 1,2,3;

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_WAREHOUSE_METERING AS
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, WAREHOUSE_ID, WAREHOUSE_NAME,
           START_TIME::DATE AS USAGE_DATE_UTC,
           SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
           SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
           SUM(CREDITS_USED) AS CREDITS_USED, COUNT(*) AS METERING_HOURS,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    GROUP BY 1,2,3,4;

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_QUERY_ATTRIBUTION AS
    WITH attr AS (
      SELECT QUERY_ID, PARENT_QUERY_ID, ROOT_QUERY_ID, WAREHOUSE_ID, WAREHOUSE_NAME,
             QUERY_TAG, USER_NAME, START_TIME, END_TIME,
             CREDITS_ATTRIBUTED_COMPUTE, CREDITS_USED_QUERY_ACCELERATION
      FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    ),
    qh AS (
      SELECT QUERY_ID, ROLE_NAME, DATABASE_NAME, SCHEMA_NAME, QUERY_TYPE, EXECUTION_STATUS,
             WAREHOUSE_SIZE, BYTES_SCANNED, TOTAL_ELAPSED_TIME, EXECUTION_TIME,
             QUEUED_OVERLOAD_TIME, BYTES_SPILLED_TO_LOCAL_STORAGE, BYTES_SPILLED_TO_REMOTE_STORAGE
      FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    )
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, a.START_TIME::DATE AS USAGE_DATE_UTC,
           a.QUERY_ID, a.PARENT_QUERY_ID, COALESCE(a.ROOT_QUERY_ID, a.QUERY_ID) AS ROOT_QUERY_ID,
           a.WAREHOUSE_ID, a.WAREHOUSE_NAME, a.USER_NAME, q.ROLE_NAME, q.DATABASE_NAME,
           q.SCHEMA_NAME, q.QUERY_TYPE, q.EXECUTION_STATUS, q.WAREHOUSE_SIZE, a.QUERY_TAG,
           a.START_TIME, a.END_TIME, a.CREDITS_ATTRIBUTED_COMPUTE,
           a.CREDITS_USED_QUERY_ACCELERATION, q.BYTES_SCANNED, q.TOTAL_ELAPSED_TIME,
           q.EXECUTION_TIME, q.QUEUED_OVERLOAD_TIME, q.BYTES_SPILLED_TO_LOCAL_STORAGE,
           q.BYTES_SPILLED_TO_REMOTE_STORAGE, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM attr a LEFT JOIN qh q ON q.QUERY_ID = a.QUERY_ID;

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_ACCT_ANOMALIES AS
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, DATE AS ANOMALY_DATE, ANOMALY_ID, IS_ANOMALY,
           ACTUAL_VALUE, GREATEST(FORECASTED_VALUE,0) AS FORECASTED_VALUE_FLOORED,
           FORECASTED_VALUE AS FORECASTED_VALUE_RAW,
           GREATEST(LOWER_BOUND,0) AS LOWER_BOUND_FLOORED, UPPER_BOUND,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ACCOUNT_USAGE.ANOMALIES_DAILY
    WHERE DATE >= DATEADD(''day'', -:retention, CURRENT_DATE());

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_QUERY_INSIGHTS AS
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, START_TIME, END_TIME, TOTAL_ELAPSED_TIME,
           QUERY_ID, QUERY_HASH, QUERY_PARAMETERIZED_HASH, WAREHOUSE_ID, WAREHOUSE_NAME,
           INSIGHT_INSTANCE_ID, INSIGHT_TYPE_ID, INSIGHT_TOPIC, IS_OPPORTUNITY,
           MESSAGE, SUGGESTIONS, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_INSIGHTS
    WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE());

  RETURN ''SP_REBUILD_LANDING_ACCOUNT complete'';
END;
';
CREATE OR REPLACE PROCEDURE SF360.LANDING.SP_REBUILD_LANDING_ACCOUNT2()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
  retention NUMBER;
BEGIN
  ALTER SESSION SET TIMEZONE = ''UTC'';
  SELECT TO_NUMBER(SETTING_VALUE) INTO :retention
    FROM SF360.CONFIG.SETTINGS WHERE SETTING_KEY = ''RETENTION_DAYS'';

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_QUERY_DAILY AS
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, START_TIME::DATE AS USAGE_DATE_UTC,
           WAREHOUSE_NAME, WAREHOUSE_SIZE, USER_NAME, ROLE_NAME, QUERY_TYPE, EXECUTION_STATUS,
           COUNT(*) AS QUERY_COUNT,
           COUNT_IF(EXECUTION_STATUS=''SUCCESS'') AS QUERY_COUNT_SUCCESS,
           SUM(BYTES_SCANNED) AS BYTES_SCANNED, SUM(ROWS_PRODUCED) AS ROWS_PRODUCED,
           SUM(TOTAL_ELAPSED_TIME) AS TOTAL_ELAPSED_MS, SUM(EXECUTION_TIME) AS EXECUTION_MS,
           SUM(QUEUED_OVERLOAD_TIME) AS QUEUED_OVERLOAD_MS, SUM(COMPILATION_TIME) AS COMPILATION_MS,
           SUM(BYTES_SPILLED_TO_LOCAL_STORAGE) AS SPILL_LOCAL_BYTES,
           SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) AS SPILL_REMOTE_BYTES,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    GROUP BY 1,2,3,4,5,6,7,8;

  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_DATA_TRANSFER_DAILY AS
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, START_TIME::DATE AS USAGE_DATE_UTC,
           TRANSFER_TYPE, SOURCE_CLOUD, SOURCE_REGION, TARGET_CLOUD, TARGET_REGION,
           SUM(BYTES_TRANSFERRED) AS BYTES_TRANSFERRED,
           SUM(BYTES_TRANSFERRED)/POWER(1024,4) AS TB_TRANSFERRED,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
    WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    GROUP BY 1,2,3,4,5,6,7;

  -- SHARES.TARGET_ACCOUNTS and LISTINGS.TARGETS are different semi-structured types,
  -- so both are cast to VARCHAR before the union.
  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_SHARING_INVENTORY AS
    WITH shares AS (
      SELECT ''SHARE''::VARCHAR AS OBJECT_KIND, NAME::VARCHAR AS OBJECT_NAME,
             DATABASE_NAME::VARCHAR AS OBJECT_DETAIL, OWNER::VARCHAR AS OWNER_NAME,
             TO_VARCHAR(TARGET_ACCOUNTS) AS TARGET_ACCOUNTS,
             LISTING_GLOBAL_NAME::VARCHAR AS LISTING_GLOBAL_NAME,
             NULL::VARCHAR AS STATE, CREATED_ON::DATE AS CREATED_DATE,
             DELETED_ON::DATE AS DELETED_DATE
      FROM SNOWFLAKE.ACCOUNT_USAGE.SHARES
    ),
    listings AS (
      SELECT ''LISTING''::VARCHAR, COALESCE(TITLE, NAME)::VARCHAR, SHARE::VARCHAR,
             OWNER::VARCHAR, TO_VARCHAR(TARGETS), GLOBAL_NAME::VARCHAR,
             STATE::VARCHAR, CREATED_ON::DATE, DELETED_ON::DATE
      FROM SNOWFLAKE.ACCOUNT_USAGE.LISTINGS
    )
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, s.*, CURRENT_TIMESTAMP() AS LOADED_AT
    FROM (SELECT * FROM shares UNION ALL SELECT * FROM listings) s;

  RETURN ''SP_REBUILD_LANDING_ACCOUNT2 complete'';
END;
';
CREATE OR REPLACE PROCEDURE SF360.LANDING.SP_REBUILD_LANDING_AI()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
  retention NUMBER;
BEGIN
  ALTER SESSION SET TIMEZONE = ''UTC'';
  SELECT TO_NUMBER(SETTING_VALUE) INTO :retention
    FROM SF360.CONFIG.SETTINGS WHERE SETTING_KEY = ''RETENTION_DAYS'';

  -- Three verified overlap traps are handled here:
  --  1. SNOWFLAKE_COCO_USAGE_HISTORY spans full history and supersedes the three legacy
  --     CORTEX_CODE_* views (identical counts, 3318 shared REQUEST_IDs).
  --  2. CORTEX_AISQL overlaps CORTEX_AI_FUNCTIONS on 667 of 669 QUERY_IDs.
  --  3. SNOWFLAKE_INTELLIGENCE and SNOWFLAKE_COWORK are byte-identical (same REQUEST_IDs).
  CREATE OR REPLACE TRANSIENT TABLE SF360.LANDING.LND_AI_USAGE_DAILY AS
    WITH aif AS (
      SELECT START_TIME, FUNCTION_NAME, MODEL_NAME, CREDITS, QUERY_ID
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    ),
    aif_ids AS (SELECT DISTINCT QUERY_ID FROM aif WHERE QUERY_ID IS NOT NULL),
    aisql_dedup AS (
      SELECT s.USAGE_TIME, s.FUNCTION_NAME, s.MODEL_NAME, s.TOKEN_CREDITS, s.TOKENS
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AISQL_USAGE_HISTORY s
      LEFT JOIN aif_ids i ON i.QUERY_ID = s.QUERY_ID
      WHERE s.USAGE_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE()) AND i.QUERY_ID IS NULL
    ),
    u AS (
      SELECT START_TIME::DATE AS D, ''AI Functions'' AS FEATURE, FUNCTION_NAME AS SUB_FEATURE,
             MODEL_NAME, NULL::VARCHAR AS USER_NAME, CREDITS, NULL::NUMBER AS TOKENS
      FROM aif
      UNION ALL
      SELECT USAGE_TIME::DATE, ''AI Functions'', FUNCTION_NAME, MODEL_NAME, NULL, TOKEN_CREDITS, TOKENS
      FROM aisql_dedup
      UNION ALL
      SELECT START_TIME::DATE, ''Cortex Agents'', AGENT_NAME, NULL, USER_NAME, TOKEN_CREDITS, TOKENS
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
      UNION ALL
      SELECT START_TIME::DATE, ''Cortex Search'', SERVICE_NAME, NULL, NULL, CREDITS, NULL
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_SERVING_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
      UNION ALL
      SELECT START_TIME::DATE, ''Cortex Analyst'', NULL, NULL, USERNAME, CREDITS, NULL
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_ANALYST_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
      UNION ALL
      SELECT START_TIME::DATE, ''Document Processing'', FUNCTION_NAME, MODEL_NAME, NULL, CREDITS_USED, NULL
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_DOCUMENT_PROCESSING_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
      UNION ALL
      SELECT USAGE_TIME::DATE, ''Cortex Code'', INTERFACE, NULL, USER_NAME, TOKEN_CREDITS, TOKENS
      FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_COCO_USAGE_HISTORY
      WHERE USAGE_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
      UNION ALL
      SELECT START_TIME::DATE, ''CoWork'', SNOWFLAKE_COWORK_NAME, NULL, USER_NAME, TOKEN_CREDITS, TOKENS
      FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_COWORK_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
      UNION ALL
      SELECT START_TIME::DATE, ''Cortex REST API'', NULL, MODEL_NAME, NULL, 0, TOKENS
      FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_REST_API_USAGE_HISTORY
      WHERE START_TIME >= DATEADD(''day'', -:retention, CURRENT_DATE())
    )
    SELECT CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME, D AS USAGE_DATE_UTC, FEATURE,
           COALESCE(SUB_FEATURE,''n/a'') AS SUB_FEATURE,
           COALESCE(MODEL_NAME,''n/a'')  AS MODEL_NAME,
           COALESCE(USER_NAME,''UNKNOWN'') AS USER_NAME,
           SUM(COALESCE(CREDITS,0)) AS CREDITS,
           SUM(COALESCE(TOKENS,0))  AS TOKENS,
           COUNT(*) AS EVENT_COUNT,
           CURRENT_TIMESTAMP() AS LOADED_AT
    FROM u GROUP BY 1,2,3,4,5,6;

  RETURN ''SP_REBUILD_LANDING_AI complete'';
END;
';

-- The six refresh tasks used to be duplicated here as well as in tasks.sql. They
-- live in the LANDING schema, so GET_DDL emitted them into this file, and running
-- it then tried to recreate the task graph -- which fails outright while the root
-- task is resumed:
--
--   091421 (22000): Unable to update graph with root task
--   SF360.LANDING.TSK_SF360_ROOT since that root task is not suspended.
--
-- tasks.sql is now the single definition of the DAG.
